INSERT INTO `LTC_MODULES` (`MODULEID`, `MODULENAME`, `URL`, `SUPERMODULEID`, `TARGET`, `STATUS`, `SYSTYPE`) VALUES ('1803', 'Ω·À„µ•¥Ú”°', '/angular/PrintSettleAccount/', '18', '2', '1', 'LC')

INSERT INTO `LTC_ROLEMODULES` (`ROLEID`, `MODULEID`) VALUES ('001', '1803')
INSERT INTO `LTC_ROLEMODULES` (`ROLEID`, `MODULEID`) VALUES ('005', '1803')
INSERT INTO `LTC_ROLEMODULES` (`ROLEID`, `MODULEID`) VALUES ('009', '1803')
INSERT INTO `LTC_ROLEMODULES` (`ROLEID`, `MODULEID`) VALUES ('564c265976', '1803')
INSERT INTO `LTC_ROLEMODULES` (`ROLEID`, `MODULEID`) VALUES ('8e411b52ce', '1803')
INSERT INTO `LTC_ROLEMODULES` (`ROLEID`, `MODULEID`) VALUES ('974bffd1bf', '1803')