//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKITEM
    {
        public string ORGID { get; set; }
        public string CHECKITEMCODE { get; set; }
        public string CHECKITEMNAME { get; set; }
        public string CHECKITEMNAMEEN { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string NORMALVALUE { get; set; }
        public string LOWBOUND { get; set; }
        public string UPBOUND { get; set; }
        public string UNITNAME { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
