//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKTEMPLATE
    {
        public CHECKTEMPLATE()
        {
            this.CHECKTEMPLATEITEM = new HashSet<CHECKTEMPLATEITEM>();
        }
    
        public string CHECKTEMPLATECODE { get; set; }
        public string CHECKTEMPLATENAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<CHECKTEMPLATEITEM> CHECKTEMPLATEITEM { get; set; }
    }
}
