//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_CAREPLANPROBLEM
    {
        public DC_CAREPLANPROBLEM()
        {
            this.DC_CAREPLANACTIVITY = new HashSet<DC_CAREPLANACTIVITY>();
            this.DC_CAREPLANDATA = new HashSet<DC_CAREPLANDATA>();
            this.DC_CAREPLANEVAL = new HashSet<DC_CAREPLANEVAL>();
            this.DC_CAREPLANGOAL = new HashSet<DC_CAREPLANGOAL>();
            this.DC_CAREPLANREASON = new HashSet<DC_CAREPLANREASON>();
        }
    
        public int CPNO { get; set; }
        public string LEVELPR { get; set; }
        public string CATEGORYTYPE { get; set; }
        public string DIAPR { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_CAREPLANACTIVITY> DC_CAREPLANACTIVITY { get; set; }
        public virtual ICollection<DC_CAREPLANDATA> DC_CAREPLANDATA { get; set; }
        public virtual ICollection<DC_CAREPLANEVAL> DC_CAREPLANEVAL { get; set; }
        public virtual ICollection<DC_CAREPLANGOAL> DC_CAREPLANGOAL { get; set; }
        public virtual ICollection<DC_CAREPLANREASON> DC_CAREPLANREASON { get; set; }
    }
}
