//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_DAYLIFECAREREC
    {
        public DC_DAYLIFECAREREC()
        {
            this.DC_DAYLIFECAREDTL = new HashSet<DC_DAYLIFECAREDTL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public string RESIDENTNO { get; set; }
        public string REGNAME { get; set; }
        public string SEX { get; set; }
        public string NURSEAIDES { get; set; }
        public Nullable<int> WEEKNUMBER { get; set; }
        public Nullable<System.DateTime> WEEKSTARTDATE { get; set; }
        public string CONTACTMATTERS { get; set; }
        public string FAMILYMESSAGE { get; set; }
        public string SOCIALWORKER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<bool> DELFLAG { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_DAYLIFECAREDTL> DC_DAYLIFECAREDTL { get; set; }
    }
}
