//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_LIFEHISTORY
    {
        public int Id { get; set; }
        public long FEENO { get; set; }
        public string NAME { get; set; }
        public string NICKNAME { get; set; }
        public string RESIDENTNO { get; set; }
        public string BIRTHPLACE { get; set; }
        public string FAMILYENVIRONMENT { get; set; }
        public string CHILDHOODEXPERIENCE { get; set; }
        public string SCHOOL { get; set; }
        public string PROUDDEEDS { get; set; }
        public string ROMANCE { get; set; }
        public string MERRYINFO { get; set; }
        public string MPORTANTPEOPLE { get; set; }
        public string WORKHISTORY { get; set; }
        public string SERVICEHISTORY { get; set; }
        public string RELIGIOUS { get; set; }
        public string LIVING { get; set; }
        public string POSITIVEPERSONALITY { get; set; }
        public string NEGATIVEPERSONALITY { get; set; }
        public string FAMILYTROUBLED { get; set; }
        public string SOOTHINGEMOTION { get; set; }
        public string SKILL { get; set; }
        public string FAVORITEDRESS { get; set; }
        public string FOODLIKE { get; set; }
        public string ANIMALLIKE { get; set; }
        public string HOLIDAYACTIVITY { get; set; }
        public string NOTLIKETHINGS { get; set; }
        public string INTERESTEDTHINGS { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
