//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_MULTITEAMCAREPLANREC
    {
        public DC_MULTITEAMCAREPLANREC()
        {
            this.DC_MULTITEAMCAREPLAN = new HashSet<DC_MULTITEAMCAREPLAN>();
        }
    
        public long FEENO { get; set; }
        public string REGNO { get; set; }
        public string NURSEAIDES { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string CHECKEDBY { get; set; }
        public long SEQNO { get; set; }
        public Nullable<int> EVALNUMBER { get; set; }
    
        public virtual ICollection<DC_MULTITEAMCAREPLAN> DC_MULTITEAMCAREPLAN { get; set; }
        public virtual DC_MULTITEAMCAREPLANEVAL DC_MULTITEAMCAREPLANEVAL { get; set; }
    }
}
