//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_NURSEINGLIFECAREREC
    {
        public DC_NURSEINGLIFECAREREC()
        {
            this.DC_NURSEINGLIFECAREDTL = new HashSet<DC_NURSEINGLIFECAREDTL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public string RESIDENTNO { get; set; }
        public string REGNAME { get; set; }
        public string SEX { get; set; }
        public string NURSEAIDES { get; set; }
        public Nullable<int> WEEKNUMBER { get; set; }
        public Nullable<System.DateTime> WEEKSTARTDATE { get; set; }
        public string SECURITYMEASURES { get; set; }
        public string ARTICLESCARRIED { get; set; }
        public string MEDICATIONINSTRUCTIONS { get; set; }
        public string ACTIVITYSUMMARY { get; set; }
        public string QUESTIONBEHAVIOR { get; set; }
        public string REMARKS { get; set; }
        public string NURSENO { get; set; }
        public string SUPERVISOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<bool> DELFLAG { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_NURSEINGLIFECAREDTL> DC_NURSEINGLIFECAREDTL { get; set; }
    }
}
