//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_NURSEINGPLANEVAL
    {
        public DC_NURSEINGPLANEVAL()
        {
            this.DC_EVALQUESTION = new HashSet<DC_EVALQUESTION>();
            this.DC_REGCPL = new HashSet<DC_REGCPL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public string REGNAME { get; set; }
        public string RESIDENTNO { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<System.DateTime> FIRSTEVALDATE { get; set; }
        public Nullable<int> EVALNUMBER { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public string HOSPITALNAME { get; set; }
        public string FAMILYSIGNATURE { get; set; }
        public string DISEASEINFO { get; set; }
        public string OPERATIONINFO { get; set; }
        public Nullable<bool> CHINESEDRUGFLAG { get; set; }
        public string CHINESEDRUG { get; set; }
        public Nullable<bool> WESTERNDRUGFLAG { get; set; }
        public string WESTERNDRUG { get; set; }
        public string VISITHOSPITALNAME { get; set; }
        public string VISITTYPE { get; set; }
        public Nullable<int> VISITNUMBER { get; set; }
        public string HEARTRATE { get; set; }
        public string BREATHTYPE { get; set; }
        public Nullable<int> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> WAISTLINE { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public Nullable<decimal> IDEALWEIGHT { get; set; }
        public string APPETITE { get; set; }
        public string FOODHABIT { get; set; }
        public string FOODTYPE { get; set; }
        public string EATTYPE { get; set; }
        public string TEETHSTATE { get; set; }
        public string GUMSSTATE { get; set; }
        public string ORALMUCOSA { get; set; }
        public string SWALLOWINGABILITY { get; set; }
        public string MASTICATORYABILITY { get; set; }
        public string STAPLEFOOD { get; set; }
        public string MEAT { get; set; }
        public string VEGETABLES { get; set; }
        public string SNACK { get; set; }
        public string SOUP { get; set; }
        public string SKINSTATE { get; set; }
        public string SKINCOLOR { get; set; }
        public string EDEMA { get; set; }
        public string SKININTEGRITY { get; set; }
        public string SKINPART { get; set; }
        public string SKINSIZE { get; set; }
        public Nullable<int> SKINLEVEL { get; set; }
        public string DEFECATION { get; set; }
        public Nullable<int> SHITNUMBER { get; set; }
        public string SHITNATURE { get; set; }
        public string SHITAMOUT { get; set; }
        public string ASSISTEDDEFECATION { get; set; }
        public string INTESTINALPERISTALSIS { get; set; }
        public string MICTURITION { get; set; }
        public string URINATIONNATURE { get; set; }
        public Nullable<bool> ACONURESISFLAG { get; set; }
        public string ACONURESISINFO { get; set; }
        public string URINATIONDISPOSAL { get; set; }
        public string RIGHTMUSCLE1 { get; set; }
        public string RIGHTMUSCLE2 { get; set; }
        public string LEFTMUSCLE1 { get; set; }
        public string LEFTMUSCLE2 { get; set; }
        public string RIGHTJOINT1 { get; set; }
        public string RIGHTJOINT2 { get; set; }
        public string LEFTJOINT1 { get; set; }
        public string LEFTJOINT2 { get; set; }
        public string GAIT { get; set; }
        public string ASSISTANTTOOL { get; set; }
        public string ASSISTANTSECURITY { get; set; }
        public string ASSISTANTSUITABILITY { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string FALLINFO { get; set; }
        public Nullable<bool> FALL1YEAR { get; set; }
        public Nullable<bool> INJUREDFLAG { get; set; }
        public string INJUREDPART { get; set; }
        public string PASTFALLINFO { get; set; }
        public string INJURYDISPOSALINFO { get; set; }
        public string PAINFREQ { get; set; }
        public string PAINLEVEL { get; set; }
        public string PAINPART { get; set; }
        public string PAINNATURE { get; set; }
        public string DURATIONTIME { get; set; }
        public string EASEPAINMETHOD { get; set; }
        public string VISUALACUITY { get; set; }
        public string ASSISTANTTOOLS { get; set; }
        public string LISTENINGSTATE { get; set; }
        public string DELUSION { get; set; }
        public string PERSONIMAGE { get; set; }
        public string ATTITUDE { get; set; }
        public string EMOTIONSTATE { get; set; }
        public string DISTURBINGENV { get; set; }
        public string SOOTHEMOTION { get; set; }
        public string BEHAVIOR { get; set; }
        public string COMMUNICATIONTYPE { get; set; }
        public string COMMUNICATIONSKILL { get; set; }
        public string PROBLEMBEHAVIOR { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public Nullable<int> INTERVALDAY { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public Nullable<bool> DELFLAG { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_EVALQUESTION> DC_EVALQUESTION { get; set; }
        public virtual ICollection<DC_REGCPL> DC_REGCPL { get; set; }
    }
}
