//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_QUESTION
    {
        public DC_QUESTION()
        {
            this.DC_QUESTIONITEM = new HashSet<DC_QUESTIONITEM>();
            this.DC_QUESTIONVALUE = new HashSet<DC_QUESTIONVALUE>();
        }
    
        public int QUESTIONID { get; set; }
        public string QUESTIONNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string QUESTIONCODE { get; set; }
        public Nullable<bool> ISSHOW { get; set; }
        public string QUESTIONDESC { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_QUESTIONITEM> DC_QUESTIONITEM { get; set; }
        public virtual ICollection<DC_QUESTIONVALUE> DC_QUESTIONVALUE { get; set; }
    }
}
