//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_QUESTIONITEM
    {
        public int ITEMID { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string ITEMNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual DC_QUESTION DC_QUESTION { get; set; }
    }
}
