//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGDAYLIFE
    {
        public int Id { get; set; }
        public long FEENO { get; set; }
        public string PAST0 { get; set; }
        public string PAST2 { get; set; }
        public string PAST4 { get; set; }
        public string PAST6 { get; set; }
        public string PAST7 { get; set; }
        public string PAST8 { get; set; }
        public string PAST9 { get; set; }
        public string PAST10 { get; set; }
        public string PAST11 { get; set; }
        public string PAST12 { get; set; }
        public string PAST14 { get; set; }
        public string PAST15 { get; set; }
        public string PAST16 { get; set; }
        public string PAST17 { get; set; }
        public string PAST18 { get; set; }
        public string PAST19 { get; set; }
        public string PAST20 { get; set; }
        public string PAST21 { get; set; }
        public string PAST22 { get; set; }
        public string PAST24 { get; set; }
        public string NOW0 { get; set; }
        public string NOW2 { get; set; }
        public string NOW4 { get; set; }
        public string NOW6 { get; set; }
        public string NOW7 { get; set; }
        public string NOW8 { get; set; }
        public string NOW9 { get; set; }
        public string NOW10 { get; set; }
        public string NOW11 { get; set; }
        public string NOW12 { get; set; }
        public string NOW14 { get; set; }
        public string NOW15 { get; set; }
        public string NOW16 { get; set; }
        public string NOW17 { get; set; }
        public string NOW18 { get; set; }
        public string NOW19 { get; set; }
        public string NOW20 { get; set; }
        public string NOW21 { get; set; }
        public string NOW22 { get; set; }
        public string NOW24 { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string NAME { get; set; }
        public string NICKNAME { get; set; }
        public string RESIDENTNO { get; set; }
        public string ORGID { get; set; }
    }
}
