//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGLIFEQUALITYEVAL
    {
        public int ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string HEALTH { get; set; }
        public string ENERGY { get; set; }
        public string MOOD { get; set; }
        public string LIVINGCONDITION { get; set; }
        public string MEMORY { get; set; }
        public string FAMILY { get; set; }
        public string MERRY { get; set; }
        public string FRIENDS { get; set; }
        public string SELF { get; set; }
        public string FAMILYABILITY { get; set; }
        public string ENTERTAINMENT { get; set; }
        public string MONEY { get; set; }
        public string WHOLELIFE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string REGNO { get; set; }
        public string ORGID { get; set; }
    }
}
