//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGCPL
    {
        public DC_REGCPL()
        {
            this.DC_ASSESSVALUE = new HashSet<DC_ASSESSVALUE>();
            this.DC_NSCPLACTIVITY = new HashSet<DC_NSCPLACTIVITY>();
            this.DC_NSCPLGOAL = new HashSet<DC_NSCPLGOAL>();
        }
    
        public long SEQNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public string EMPNO { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<int> NEEDDAYS { get; set; }
        public Nullable<System.DateTime> TARGETDATE { get; set; }
        public string MAJORTYPE { get; set; }
        public string CPLEVEL { get; set; }
        public string CPDIA { get; set; }
        public Nullable<long> ID { get; set; }
        public string NSDESC { get; set; }
        public string CPREASON { get; set; }
        public Nullable<bool> FINISHFLAG { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public Nullable<int> TOTALDAYS { get; set; }
        public string CPRESULT { get; set; }
        public string UNFINISHREASON { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_ASSESSVALUE> DC_ASSESSVALUE { get; set; }
        public virtual ICollection<DC_NSCPLACTIVITY> DC_NSCPLACTIVITY { get; set; }
        public virtual ICollection<DC_NSCPLGOAL> DC_NSCPLGOAL { get; set; }
        public virtual DC_NURSEINGPLANEVAL DC_NURSEINGPLANEVAL { get; set; }
    }
}
