//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGQUESTIONEVALREC
    {
        public DC_REGQUESTIONEVALREC()
        {
            this.DC_REGEVALQUESTION = new HashSet<DC_REGEVALQUESTION>();
        }
    
        public int EVALRECID { get; set; }
        public Nullable<float> SCORE { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public string EVALRESULT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string CHECKEDBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_REGEVALQUESTION> DC_REGEVALQUESTION { get; set; }
    }
}
