//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGFILE
    {
        public DC_REGFILE()
        {
            this.DC_IPDREG = new HashSet<DC_IPDREG>();
        }
    
        public string REGNO { get; set; }
        public string REGNAME { get; set; }
        public string NICKNAME { get; set; }
        public string SEX { get; set; }
        public string BIRTHPLACE { get; set; }
        public string ORIGINPLACE { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string IDNO { get; set; }
        public string PTYPE { get; set; }
        public string PHONE { get; set; }
        public string LIVINGADDRESS { get; set; }
        public string PERMANENTADDRESS { get; set; }
        public string LANGUAGE { get; set; }
        public string EDUCATION { get; set; }
        public string PROFESSION { get; set; }
        public string MERRYSTATE { get; set; }
        public string RELIGION { get; set; }
        public string ECONOMICSOURCES { get; set; }
        public string LIVCONDITION { get; set; }
        public string SOURCETYPE { get; set; }
        public string OBSTACLEMANUAL { get; set; }
        public string SURETYNAME { get; set; }
        public Nullable<int> SURETYAGE { get; set; }
        public string SURETYUNIT { get; set; }
        public string SURETYTITLE { get; set; }
        public string SURETYADDRESS { get; set; }
        public string SURETYEMAIL { get; set; }
        public string SURETYPHONE { get; set; }
        public string SURETYMOBILE { get; set; }
        public string CONTACTNAME1 { get; set; }
        public Nullable<int> CONTACTAGE1 { get; set; }
        public string CONTACTUNIT1 { get; set; }
        public string CONTACTTITLE1 { get; set; }
        public string CONTACTADDRESS1 { get; set; }
        public string CONTACTEMAIL1 { get; set; }
        public string CONTACTPHONE1 { get; set; }
        public string CONTACTMOBILE1 { get; set; }
        public string CONTACTNAME2 { get; set; }
        public Nullable<int> CONTACTAGE2 { get; set; }
        public string CONTACTUNIT2 { get; set; }
        public string CONTACTTITLE2 { get; set; }
        public string CONTACTADDRESS2 { get; set; }
        public string CONTACTEMAIL2 { get; set; }
        public string CONTACTPHONE2 { get; set; }
        public string CONTACTMOBILE2 { get; set; }
        public string DISEASEINFO { get; set; }
        public string ECOLOGICALMAP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string CHECKDATE { get; set; }
        public string CHECKEDBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_IPDREG> DC_IPDREG { get; set; }
    }
}
