//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGMEDICINE
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public string REGNAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string RESIDENTNO { get; set; }
        public string MEDICINENAME { get; set; }
        public string HOSPITALNAME { get; set; }
        public string DEPTNAME { get; set; }
        public string TAKEQTY { get; set; }
        public string TAKEPROC { get; set; }
        public string TAKEDATETIME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> BREAKDATE { get; set; }
        public string BREAKREASON { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
