//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGBASEINFOLIST
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<int> CNT { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNAME { get; set; }
        public string RESIDENTNO { get; set; }
        public string CONTACTNAME { get; set; }
        public string CONTACTPHONE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string LANGUAGE { get; set; }
        public string VS { get; set; }
        public string JOB { get; set; }
        public string RELIGION { get; set; }
        public string MERRYSTATE { get; set; }
        public string EDUCATION { get; set; }
        public string HEIGHT { get; set; }
        public string WEIGHT { get; set; }
        public string BMI { get; set; }
        public string WAISTLINE { get; set; }
        public string DISEASEHISTORY { get; set; }
        public string ADLSCORE { get; set; }
        public string IADLSCORE { get; set; }
        public string MMSESCORE { get; set; }
        public string GDSSCORE { get; set; }
        public string UPPERDISORDER { get; set; }
        public string LOWERDISORDER { get; set; }
        public string APHASIA { get; set; }
        public string VISUALLYIMPAIRED { get; set; }
        public string HEARINGIMPAIRED { get; set; }
        public string FALSETEETHU { get; set; }
        public string FALSETEETHL { get; set; }
        public string NOTEATFOOD { get; set; }
        public string LIKEFOOD { get; set; }
        public string QUESTIONBEHAVIOR { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string XRAY { get; set; }
        public string SYPHILIS { get; set; }
        public string AIDS { get; set; }
        public string HBSAG { get; set; }
        public string AMIBADYSENTERY { get; set; }
        public string INSECTEGG { get; set; }
        public string BACILLUSDYSENTERY { get; set; }
        public Nullable<System.DateTime> NEXTCHECKDATE { get; set; }
        public string MEDICINE { get; set; }
        public string NURSENO { get; set; }
        public string SUPERVISOR { get; set; }
        public string DIRECTOR { get; set; }
        public string REGNO { get; set; }
        public string ORGID { get; set; }
    }
}
