//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGACTIVITYREQUESTEVAL
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<int> INTERVALDAY { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public string REGNAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string EDUCATION { get; set; }
        public string MERRYSTATE { get; set; }
        public string PROFESSION { get; set; }
        public string LANGUAGE { get; set; }
        public string SKILL { get; set; }
        public string INTERESTING { get; set; }
        public string VISUALACUITY { get; set; }
        public string LISTENINGSTATE { get; set; }
        public string DELUSION { get; set; }
        public string VISUALILLUSION { get; set; }
        public string MMSESCORE { get; set; }
        public string MMSEITEMRESULT { get; set; }
        public string MMSERESULT { get; set; }
        public string ADLSCORE { get; set; }
        public string ADLITEMRESULT { get; set; }
        public string ADLRESULT { get; set; }
        public string IADLSCORE { get; set; }
        public string IADLITEMRESULT { get; set; }
        public string IADLRESULT { get; set; }
        public string GDSSCORE { get; set; }
        public string GDSITEMRESULT { get; set; }
        public string GDSRESULT { get; set; }
        public string EMOTIONSTATE { get; set; }
        public string PROBLEMBEHAVIOR { get; set; }
        public string INTERPERSONAL { get; set; }
        public string SELF { get; set; }
        public string PROMOTION { get; set; }
        public string PROMOTIONSTRATEGY { get; set; }
        public string PRESERVE { get; set; }
        public string PRESERVESTRATEGY { get; set; }
        public string EASE { get; set; }
        public string EASESTRATEGY { get; set; }
        public Nullable<bool> DELFLAG { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public string ORGID { get; set; }
    }
}
