//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGCHECKRECORD
    {
        public DC_REGCHECKRECORD()
        {
            this.DC_REGCHECKRECORDDATA = new HashSet<DC_REGCHECKRECORDDATA>();
        }
    
        public long RECORDID { get; set; }
        public string REGNO { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string CHECKTEMPLATECODE { get; set; }
        public string ACTIONUSERCODE { get; set; }
        public Nullable<bool> ISABNORMAL { get; set; }
        public Nullable<bool> TRACESTATUS { get; set; }
        public Nullable<System.DateTime> TRACEDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_REGCHECKRECORDDATA> DC_REGCHECKRECORDDATA { get; set; }
    }
}
