//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_SWREGEVALPLAN
    {
        public DC_SWREGEVALPLAN()
        {
            this.DC_TASKGOALSSTRATEGY = new HashSet<DC_TASKGOALSSTRATEGY>();
        }
    
        public long EVALPLANID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string RESIDENTNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<int> EVALNUMBER { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public string REGNAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string IDNO { get; set; }
        public string CONTACTNAME { get; set; }
        public string CONTACTPHONE { get; set; }
        public string CONTACTMOBILE { get; set; }
        public string APPELLATION { get; set; }
        public string LIVINGADDRESS { get; set; }
        public string PTYPE { get; set; }
        public string OBSTACLEMANUAL { get; set; }
        public string SOURCETYPE { get; set; }
        public string TAKECAREREASON { get; set; }
        public string TAKECARETYPE { get; set; }
        public string SERVICETYPE { get; set; }
        public string DISEASEINFO { get; set; }
        public string ECOLOGICALMAP { get; set; }
        public string PERSONALHISTORY { get; set; }
        public string PHYSIOLOGY { get; set; }
        public string PSYCHOLOGY { get; set; }
        public string FAMILYSUPPORT { get; set; }
        public string ECONOMICCAPACITY { get; set; }
        public string SOCIALRESOURCES { get; set; }
        public string SOCIALRESOURCE { get; set; }
        public string CURRENTSUBSIDY { get; set; }
        public string ASSISTAPPLICATION { get; set; }
        public string MMSE { get; set; }
        public string ADL { get; set; }
        public string IADL { get; set; }
        public string GDS { get; set; }
        public string EMOTIONSTATE { get; set; }
        public string BEHAVIOR { get; set; }
        public string ATTITUDE { get; set; }
        public string PAYATTENTION { get; set; }
        public string THOUGHT { get; set; }
        public string UNDERSTANDABILITY { get; set; }
        public string SOCIALABILITY { get; set; }
        public string EYESIGHT { get; set; }
        public string HEARING { get; set; }
        public string EXPRESSION { get; set; }
        public string UNDERSTANDING { get; set; }
        public string FAMILYINTERACTION { get; set; }
        public string RELATIVEINTERACTION { get; set; }
        public string FRIENDINTERACTION { get; set; }
        public string ELDERINTERACTION { get; set; }
        public string ADAPTIVESTATE { get; set; }
        public string LIVINGCONDITION { get; set; }
        public string JOBINFO { get; set; }
        public string DAYTAKECAREHOUR { get; set; }
        public Nullable<bool> RELATIVESNEEDCARE { get; set; }
        public Nullable<bool> REPLACEMENT { get; set; }
        public Nullable<bool> EASEPRESSURE { get; set; }
        public string LIFEQUALITY { get; set; }
        public string FAMILYEXPECT { get; set; }
        public string ORGID { get; set; }
        public string REGNO { get; set; }
        public Nullable<bool> DELFLAG { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
    
        public virtual ICollection<DC_TASKGOALSSTRATEGY> DC_TASKGOALSSTRATEGY { get; set; }
    }
}
