//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_TEAMACTIVITY
    {
        public DC_TEAMACTIVITY()
        {
            this.DC_TEAMACTIVITYDTL = new HashSet<DC_TEAMACTIVITYDTL>();
        }
    
        public int SEQNO { get; set; }
        public string ACTIVITYCODE { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_TEAMACTIVITYDTL> DC_TEAMACTIVITYDTL { get; set; }
    }
}
