//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_TASKREMIND
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> ASSIGNDATE { get; set; }
        public string ASSIGNEDBY { get; set; }
        public string ASSIGNEDNAME { get; set; }
        public string ASSIGNEE { get; set; }
        public string ASSIGNNAME { get; set; }
        public string CONTENT { get; set; }
        public Nullable<bool> RECSTATUS { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public string UNFINISHREASON { get; set; }
        public Nullable<System.DateTime> PERFORMDATE { get; set; }
        public string URL { get; set; }
        public Nullable<bool> NEWRECFLAG { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string ORGID { get; set; }
    }
}
