//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_TEAMACTIVITYDTL
    {
        public int ID { get; set; }
        public Nullable<int> SEQNO { get; set; }
        public string TITLENAME { get; set; }
        public string ITEMNAME { get; set; }
    
        public virtual DC_TEAMACTIVITY DC_TEAMACTIVITY { get; set; }
    }
}
