//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BEDBASIC
    {
        public string BEDNO { get; set; }
        public string BEDDESC { get; set; }
        public string ROOMNO { get; set; }
        public string BEDCLASS { get; set; }
        public string FLOOR { get; set; }
        public string DEPTNO { get; set; }
        public string BEDTYPE { get; set; }
        public string BEDKIND { get; set; }
        public string BEDSTATUS { get; set; }
        public string SEXTYPE { get; set; }
        public string PRESTATUS { get; set; }
        public string INSBEDFLAG { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public string ORGID { get; set; }
        public Nullable<long> FEENO { get; set; }
    }
}
