//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_FALLINCIDENTEVENT
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string RECORDBY { get; set; }
        public string EVENTADDRESS { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public string EVENTTYPE { get; set; }
        public string EVENTDEGREE { get; set; }
        public string EVENTCAUSE { get; set; }
        public string CONSCIOUSSTATE { get; set; }
        public string EMOTIONALSTATE { get; set; }
        public string SIGNS { get; set; }
        public string EVENTDESC { get; set; }
        public string SETTLEBY { get; set; }
        public Nullable<System.DateTime> VISITDOCDATE { get; set; }
        public string HOSPNAME { get; set; }
        public string NOTIFYPEOPLE { get; set; }
        public Nullable<bool> NOTIFYGOVFLAG { get; set; }
        public Nullable<System.DateTime> NOTIFYDATE { get; set; }
        public string CONSCIOUSSTATE_A { get; set; }
        public string EMOTIONSTATE_A { get; set; }
        public string SETTLERESULT { get; set; }
        public string FOLLOWUPINSTRUCTIONS { get; set; }
        public string MEDICALDISPUTE { get; set; }
        public string AFFECTS { get; set; }
        public string AFFECTSDESC { get; set; }
        public string IMPROVEMENT { get; set; }
        public string DESCRIPTION { get; set; }
        public string ORGID { get; set; }
        public string PICT1 { get; set; }
        public string PICT2 { get; set; }
    }
}
