//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_DRGFREQREF
    {
        public string FREQNO { get; set; }
        public string FREQNAME { get; set; }
        public Nullable<int> FREQHOUR { get; set; }
        public Nullable<int> FREQDAY { get; set; }
        public Nullable<int> FREQQTY { get; set; }
        public string FREQMOR { get; set; }
        public string FREQNOON { get; set; }
        public string FREQEVE { get; set; }
        public string FREQSLEEP { get; set; }
        public string FREQMEAL { get; set; }
        public string FREQTIME { get; set; }
        public string FREQPRN { get; set; }
        public string FREQFLG { get; set; }
        public string FREQWEEK { get; set; }
        public string STATEFLAG { get; set; }
        public string CREATEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEID { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    }
}
