//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_UNPLANEDIPD
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public Nullable<bool> CHARGEFLAG { get; set; }
        public string IPDDIAG { get; set; }
        public Nullable<bool> EPDFLAG { get; set; }
        public string IPDCAUSE { get; set; }
        public Nullable<bool> H72IPD { get; set; }
        public Nullable<bool> UNPLANFLAG { get; set; }
        public Nullable<bool> CATHETERFLAG { get; set; }
        public string HOSPNAME { get; set; }
        public string ESCORTPEOPLE { get; set; }
        public string ESCORTRELATION { get; set; }
        public string IPDDESC { get; set; }
        public string MRSUMMARY { get; set; }
        public Nullable<decimal> DEPOSITAMT { get; set; }
        public string DEPOSITDESC { get; set; }
        public string OUTREASON { get; set; }
        public Nullable<bool> OUTFLAG { get; set; }
        public Nullable<System.DateTime> OUTDATE { get; set; }
        public Nullable<int> IPDDAYS { get; set; }
        public string PAYOUTWAY { get; set; }
        public Nullable<decimal> PAYAMT { get; set; }
        public string BEDTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ORGID { get; set; }
    }
}
