//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PROPOSALDISSCUSS
    {
        public LTC_PROPOSALDISSCUSS()
        {
            this.LTC_PROPOSALDISSCUSSREC = new HashSet<LTC_PROPOSALDISSCUSSREC>();
        }
    
        public long RECORDID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> PROPOSALDATE { get; set; }
        public string PROPOSALBY { get; set; }
        public Nullable<System.DateTime> NEXTPROPOSALDATE { get; set; }
        public string PERSONALHIST { get; set; }
        public string PROBLEMANALYSIS { get; set; }
        public string RESOURCEEVAL { get; set; }
        public string PROCESSPLAN { get; set; }
        public string ASSESSMENTS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string TITLE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_PROPOSALDISSCUSSREC> LTC_PROPOSALDISSCUSSREC { get; set; }
    }
}
