//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NCISUPERVISE
    {
        public int ID { get; set; }
        public long FEENO { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public int TYPE { get; set; }
        public Nullable<System.DateTime> NEXTSTARTDATE { get; set; }
        public bool STATUS { get; set; }
        public string CREATEBY { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    }
}
