//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CHECKREC
    {
        public LTC_CHECKREC()
        {
            this.LTC_CHECKRECDTL = new HashSet<LTC_CHECKRECDTL>();
        }
    
        public long RECORDID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string RECORDBY { get; set; }
        public string HOSPNAME { get; set; }
        public string CHECKRESULTS { get; set; }
        public Nullable<System.DateTime> NEXTCHECKDATE { get; set; }
        public string NEXTCHECKBY { get; set; }
        public string TRACESTATE { get; set; }
        public string DISEASEDESC { get; set; }
        public Nullable<bool> XRAYFLAG { get; set; }
        public Nullable<bool> NORMALFLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_CHECKRECDTL> LTC_CHECKRECDTL { get; set; }
    }
}
