//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_INFECTIONSYMPOTM
    {
        public long ID { get; set; }
        public Nullable<long> SEQNO { get; set; }
        public string ITEMNAME { get; set; }
        public string SYMPOTM { get; set; }
        public Nullable<System.DateTime> OCCURDATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ITEMNO { get; set; }
    
        public virtual LTC_INFECTIONIND LTC_INFECTIONIND { get; set; }
    }
}
