//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGDISEASEHISDTL
    {
        public int ID { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public string OTHERITEMNAME { get; set; }
        public string SCENARIOOPTIONIDS { get; set; }
        public Nullable<System.DateTime> SICKTIME { get; set; }
        public string ORGITREATMENTHOS { get; set; }
        public string EXPECTTRANSFERTO { get; set; }
        public Nullable<bool> HAVECURE { get; set; }
    
        public virtual LTC_REGDISEASEHIS LTC_REGDISEASEHIS { get; set; }
    }
}
