//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ROLES
    {
        public LTC_ROLES()
        {
            this.LTC_MODULES = new HashSet<LTC_MODULES>();
            this.LTC_USERS = new HashSet<LTC_USERS>();
        }
    
        public string ROLEID { get; set; }
        public string ROLENAME { get; set; }
        public string ROLETYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string ORGID { get; set; }
        public string SYSTYPE { get; set; }
    
        public virtual ICollection<LTC_MODULES> LTC_MODULES { get; set; }
        public virtual ICollection<LTC_USERS> LTC_USERS { get; set; }
    }
}
