//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CHECKRECDTL
    {
        public long ID { get; set; }
        public string CHECKTYPE { get; set; }
        public string CHECKITEM { get; set; }
        public string CHECKRESULTS { get; set; }
        public string DESCRIPTION { get; set; }
        public string EVALCOMBO { get; set; }
        public Nullable<long> RECORDID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
    
        public virtual LTC_CHECKREC LTC_CHECKREC { get; set; }
    }
}
