//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NURSINGHANDOVER
    {
        public int ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string CONTENT_D { get; set; }
        public string CONTENT_E { get; set; }
        public string CONTENT_N { get; set; }
        public Nullable<System.DateTime> RECDATE_D { get; set; }
        public Nullable<System.DateTime> RECDATE_E { get; set; }
        public Nullable<System.DateTime> RECDATE_N { get; set; }
        public string RECORDBY_D { get; set; }
        public string RECORDBY_E { get; set; }
        public string RECORDBY_N { get; set; }
        public string NURSE_D { get; set; }
        public string NURSE_E { get; set; }
        public string NURSE_N { get; set; }
        public Nullable<bool> PRINTFLAG { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
