//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_GOODS
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public string BarNo { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> LoanPrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<int> InventoryQuantity { get; set; }
        public Nullable<int> InventoryBaseline { get; set; }
        public Nullable<int> TotalLoanAmount { get; set; }
        public Nullable<int> TotalSaleAmount { get; set; }
        public Nullable<bool> NotLess { get; set; }
        public Nullable<bool> IsPayItem { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public string OrgId { get; set; }
    }
}
