//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NSMEDICALMATERIAL
    {
        public LTC_NSMEDICALMATERIAL()
        {
            this.LTC_MATERIALRECORD = new HashSet<LTC_MATERIALRECORD>();
        }
    
        public int MATERIALID { get; set; }
        public string CHARGETYPEID { get; set; }
        public string ACCOUNTINGID { get; set; }
        public string NSID { get; set; }
        public string MCRULEID { get; set; }
        public bool ISNCIITEM { get; set; }
        public string MCMATERIALCODE { get; set; }
        public string NSMATERIALCODE { get; set; }
        public string MATERIALTYPE { get; set; }
        public string MATERIALNAME { get; set; }
        public string MATERIALLEVEL { get; set; }
        public bool ISCHINAPRODUCT { get; set; }
        public string PROVIDER { get; set; }
        public string ORGIN { get; set; }
        public string MANUFACTURER { get; set; }
        public string SPEC { get; set; }
        public string UNITS { get; set; }
        public decimal UNITPRICE { get; set; }
        public string USAGE { get; set; }
        public string ATTENTION { get; set; }
        public Nullable<decimal> GUIDEPRICE { get; set; }
        public Nullable<decimal> MAXPRICE { get; set; }
        public Nullable<int> NCIMONTHLYMAXUSAGE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public string PINYIN { get; set; }
        public int STATUS { get; set; }
        public bool ISREQUIREUPDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<LTC_MATERIALRECORD> LTC_MATERIALRECORD { get; set; }
    }
}
