//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COSTGROUPDTL
    {
        public int ID { get; set; }
        public int GROUPID { get; set; }
        public string COSTITEMNO { get; set; }
        public string COSTNAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PERIOD { get; set; }
        public Nullable<int> REPEATCOUNT { get; set; }
        public Nullable<int> COSTITEMID { get; set; }
        public string ITEMUNIT { get; set; }
    
        public virtual LTC_COSTGROUP LTC_COSTGROUP { get; set; }
    }
}
