//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BILLV2
    {
        public LTC_BILLV2()
        {
            this.LTC_FEERECORD = new HashSet<LTC_FEERECORD>();
            this.LTC_NCIDEDUCTION = new HashSet<LTC_NCIDEDUCTION>();
        }
    
        public string BILLID { get; set; }
        public Nullable<int> BILLPAYID { get; set; }
        public string BILLMONTH { get; set; }
        public Nullable<int> REFUNDRECORDID { get; set; }
        public long FEENO { get; set; }
        public decimal NCIITEMTOTALCOST { get; set; }
        public decimal SELFPAY { get; set; }
        public Nullable<decimal> NCIPAYLEVEL { get; set; }
        public Nullable<decimal> NCIPAYSCALE { get; set; }
        public decimal NCIPAY { get; set; }
        public decimal NCIITEMSELFPAY { get; set; }
        public Nullable<System.DateTime> BALANCESTARTTIME { get; set; }
        public System.DateTime BALANCEENDTIME { get; set; }
        public Nullable<int> HOSPDAY { get; set; }
        public int STATUS { get; set; }
        public string BILLCREATOR { get; set; }
        public string BALANCEOPERATOR { get; set; }
        public string REFUNDOPERATOR { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISFINANCIALCLOSE { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string ORGID { get; set; }
    
        public virtual LTC_BILLV2PAY LTC_BILLV2PAY { get; set; }
        public virtual LTC_REFUND LTC_REFUND { get; set; }
        public virtual ICollection<LTC_FEERECORD> LTC_FEERECORD { get; set; }
        public virtual ICollection<LTC_NCIDEDUCTION> LTC_NCIDEDUCTION { get; set; }
    }
}
