//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_HOMECARESUPERVISE
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> SUPERVISEDATE { get; set; }
        public string OPERATOR { get; set; }
        public string SUPERVISOR { get; set; }
        public string CONTACTTYPE { get; set; }
        public Nullable<int> MINUTES { get; set; }
        public string SUPERVISEDESC { get; set; }
        public string ASSESSMENT { get; set; }
        public string PROCESSDESC { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CONTACTDATE { get; set; }
        public string ORGID { get; set; }
    }
}
