//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_SCENARIO_ITEM
    {
        public LTC_SCENARIO_ITEM()
        {
            this.LTC_SCENARIO_ITEM_OPTION = new HashSet<LTC_SCENARIO_ITEM_OPTION>();
        }
    
        public int ID { get; set; }
        public int CATEGORYID { get; set; }
        public Nullable<int> GROUPID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public string ITEMNAME { get; set; }
    
        public virtual LTC_SCENARIO LTC_SCENARIO { get; set; }
        public virtual ICollection<LTC_SCENARIO_ITEM_OPTION> LTC_SCENARIO_ITEM_OPTION { get; set; }
    }
}
