//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGRELATIONDTL
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string CONTREL { get; set; }
        public string KINSHIP { get; set; }
        public string RELATIONTYPE { get; set; }
        public Nullable<bool> LIVINGFLAG { get; set; }
        public string EDUCATION { get; set; }
        public string MERRYFLAG { get; set; }
        public string HEALTHFLAG { get; set; }
        public string DEATHFLAG { get; set; }
        public string WORKCODE { get; set; }
        public Nullable<bool> ECONOMYFLAG { get; set; }
        public string IDNO { get; set; }
        public string ZIP { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS2 { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string SKYPE { get; set; }
        public string MSN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string ECONOMYABILITY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
    }
}
