//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CONSTRAINTREC
    {
        public LTC_CONSTRAINTREC()
        {
            this.LTC_CONSTRAINSBEVAL = new HashSet<LTC_CONSTRAINSBEVAL>();
        }
    
        public long SEQNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public string CLASSTYPE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public string REASON { get; set; }
        public string EXECREASON { get; set; }
        public string CONSTRAINTWAY { get; set; }
        public string BODYPART { get; set; }
        public string CONSTRAINTWAYCNT { get; set; }
        public Nullable<bool> CANCELFLAG { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string DURATION { get; set; }
        public string CANCELREASON { get; set; }
        public string CANCELEXECBY { get; set; }
        public Nullable<bool> CANCEL24FLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_CONSTRAINSBEVAL> LTC_CONSTRAINSBEVAL { get; set; }
    }
}
