//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_SCENARIO_ITEM_OPTION
    {
        public int ID { get; set; }
        public Nullable<int> SCENARIOITEMID { get; set; }
        public Nullable<int> OPTIONID { get; set; }
        public string OPTIONNAME { get; set; }
    
        public virtual LTC_SCENARIO_ITEM LTC_SCENARIO_ITEM { get; set; }
    }
}
