//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_VISITHOSPITAL
    {
        public LTC_VISITHOSPITAL()
        {
            this.LTC_VISITDEPT = new HashSet<LTC_VISITDEPT>();
            this.LTC_VISITDOCTOR = new HashSet<LTC_VISITDOCTOR>();
        }
    
        public string HOSPNO { get; set; }
        public string HOSPNAME { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_VISITDEPT> LTC_VISITDEPT { get; set; }
        public virtual ICollection<LTC_VISITDOCTOR> LTC_VISITDOCTOR { get; set; }
    }
}
