//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_FSTREGREC
    {
        public int ID { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> REGTIME { get; set; }
        public string SUBJECT { get; set; }
        public string PRESENTILLNESS { get; set; }
        public Nullable<bool> PREVHXFLAG { get; set; }
        public string PREVHX { get; set; }
        public Nullable<bool> MARRYFLAG { get; set; }
        public Nullable<bool> OFFSPRINGFLAG { get; set; }
        public string OFFSPRING { get; set; }
        public string MENELIPSIS { get; set; }
        public Nullable<System.DateTime> LMP { get; set; }
        public Nullable<bool> MEDHFLAG { get; set; }
        public string MEDH { get; set; }
        public Nullable<bool> ALLERGICHFLAG { get; set; }
        public string ALLERGICH { get; set; }
        public Nullable<bool> OPERATIONHXFLAG { get; set; }
        public string OPERATIONHX { get; set; }
        public Nullable<bool> PERSONALHXFLAG { get; set; }
        public string PERSONALHX { get; set; }
        public Nullable<bool> FHXFLAG { get; set; }
        public string FHX { get; set; }
        public string TEMP { get; set; }
        public Nullable<decimal> PULSE { get; set; }
        public Nullable<decimal> BREATH { get; set; }
        public Nullable<decimal> DP { get; set; }
        public Nullable<decimal> SP { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<bool> SKINMUCOSAHRUNFLAG { get; set; }
        public Nullable<bool> SKINMUCOSAHRANFLAG { get; set; }
        public Nullable<bool> SKINMUCOSACBFLAG { get; set; }
        public Nullable<bool> SKINMUCOSAQBFLAG { get; set; }
        public Nullable<bool> SKINMUCOSAPZFLAG { get; set; }
        public Nullable<bool> OTHERSKINMUCOSAFLAG { get; set; }
        public string SKINMUCOSA { get; set; }
        public string OTHERSKINMUCOSA { get; set; }
        public Nullable<bool> LYMPHGLANDFLAG { get; set; }
        public string LYMPHGLAND { get; set; }
        public Nullable<bool> HEADFLAG { get; set; }
        public Nullable<bool> SCLERAFLAG { get; set; }
        public Nullable<bool> EBFLAG { get; set; }
        public string EB { get; set; }
        public Nullable<bool> CONJUNCTIVAFLAG { get; set; }
        public string OTHERCONJUNCTIVA { get; set; }
        public Nullable<bool> EARFLAG { get; set; }
        public string EAR { get; set; }
        public string ACOUSTICDUCTPRO { get; set; }
        public string ACOUSTICDUCT { get; set; }
        public string NASALSEPTUMPRO { get; set; }
        public string NASALSEPTUM { get; set; }
        public string NASALMUCOSA { get; set; }
        public string NASALSHOULDER { get; set; }
        public string LIP { get; set; }
        public string TONGUE { get; set; }
        public string ORALMUCOSAPRO { get; set; }
        public string ORALMUCOSA { get; set; }
        public string TOOTH { get; set; }
        public string TONSIL { get; set; }
        public string TONSILC { get; set; }
        public string TONSILD { get; set; }
        public string TONSILHN { get; set; }
        public string ORGAN { get; set; }
        public string THYROIDGLAND { get; set; }
        public string THYROIDGLANDC { get; set; }
        public string THYROIDGLANDD { get; set; }
        public Nullable<bool> THORAXFLAG { get; set; }
        public string THORAX { get; set; }
        public string LUNGPRO { get; set; }
        public Nullable<bool> LUNGGLYFLAG { get; set; }
        public string LUNGG { get; set; }
        public Nullable<bool> LUNGSLYFLAG { get; set; }
        public string LUNGS { get; set; }
        public Nullable<int> HEARTRATE { get; set; }
        public Nullable<bool> HEARTRHYTHMFLAG { get; set; }
        public string HEARTRHYTHM { get; set; }
        public string HEARTSOUND { get; set; }
        public Nullable<bool> BREASTDCFLAG { get; set; }
        public Nullable<bool> BREASTBKFLAG { get; set; }
        public string BREAST { get; set; }
        public string OTHERBREAST { get; set; }
        public string NIPPLEPRO { get; set; }
        public string NIPPLEFMWPRO { get; set; }
        public string NIPPLE { get; set; }
        public string OTHERNIPPLE { get; set; }
        public string ABDOMENPRO { get; set; }
        public Nullable<bool> ABDOMENBZFFLAG { get; set; }
        public string ABDOMEN { get; set; }
        public string BOWELSOUNDPRO { get; set; }
        public string BOWELSOUNDKJ { get; set; }
        public string BOWELSOUNDJR { get; set; }
        public string OTHERBOWELSOUND { get; set; }
        public string SPINELIMBSPRO { get; set; }
        public string SPINELIMBSJXPRO { get; set; }
        public string SPINELIMBSBW { get; set; }
        public string SPINELIMBSJX { get; set; }
        public string ANUSGENITALIAPRO { get; set; }
        public string OTHERANUSGENITALIAPRO { get; set; }
        public string NERVOUS { get; set; }
        public string NERVOUSC { get; set; }
        public string NERVOUSL { get; set; }
        public string OTHERNERVOUS { get; set; }
        public string OTHERDEPTEXAM { get; set; }
        public Nullable<bool> PAINFLAG { get; set; }
        public string PAINSCORE { get; set; }
        public string PAINPOSITION { get; set; }
        public string PAINPROPERTY { get; set; }
        public string PAINFREQ { get; set; }
        public Nullable<bool> NUTRITIONALFLAG { get; set; }
        public string NUTRITIONAL { get; set; }
        public Nullable<bool> REHAGNEEDS { get; set; }
        public string SPECIALNEEDSTOOTH { get; set; }
        public string SPECIALNEEDHEAR { get; set; }
        public string SPECIALNEEDHEARPOS { get; set; }
        public string SPECIALNEEDVISION { get; set; }
        public string SPECIALNEEDVISIONPOS { get; set; }
        public string MISSIONOBJ { get; set; }
        public Nullable<bool> LEARNABILITY { get; set; }
        public string LEARNWISH { get; set; }
        public Nullable<bool> LEARNNEEDFLAG { get; set; }
        public string LEARNNEED { get; set; }
        public string TENTATIVEDIAG { get; set; }
        public string PLAN { get; set; }
        public string HANDLE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
