//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CARERSVRREC
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string CARER { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string SVRADDRESS { get; set; }
        public string SVRTYPE { get; set; }
        public string SVRPEOPLE { get; set; }
        public string RELATIONTYPE { get; set; }
        public string QUESTIONLEVEL { get; set; }
        public string QUESTIONFOCUS { get; set; }
        public string PROCESSACTIVITY { get; set; }
        public string SVRFOCUS { get; set; }
        public string QUESTIONDESC { get; set; }
        public string TREATDESC { get; set; }
        public string EVALSTATUS { get; set; }
        public Nullable<int> EVALMINUTES { get; set; }
        public string EVALDESC { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
