//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PREIPD
    {
        public long PREFEENO { get; set; }
        public string RECSTATUS { get; set; }
        public string SOURCETYPE { get; set; }
        public string INSMARK { get; set; }
        public Nullable<System.DateTime> PREDATE { get; set; }
        public string DEPTNO { get; set; }
        public string BEDNO { get; set; }
        public string COMMDESC { get; set; }
        public Nullable<bool> WAITFLAG { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public string ORGID { get; set; }
        public string CONTACTTEL { get; set; }
        public string CONTACTNAME { get; set; }
        public string CANCELREASON { get; set; }
        public string PNAME { get; set; }
        public string SEX { get; set; }
        public Nullable<int> AGE { get; set; }
        public string IDNO { get; set; }
        public string Phone { get; set; }
    }
}
