//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_VISITDOCTOR
    {
        public string DOCNO { get; set; }
        public string DOCNAME { get; set; }
        public string HOSPNO { get; set; }
        public string DEPTNO { get; set; }
    
        public virtual LTC_VISITDEPT LTC_VISITDEPT { get; set; }
        public virtual LTC_VISITHOSPITAL LTC_VISITHOSPITAL { get; set; }
    }
}
