//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PIPELINEREC
    {
        public int SEQNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string PIPELINENAME { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<bool> REMOVEFLAG { get; set; }
        public string REMOVETRAIN { get; set; }
        public Nullable<bool> REMOVEDFLAG { get; set; }
        public Nullable<System.DateTime> REMOVEDATE { get; set; }
        public string REMOVEREASON { get; set; }
        public string REMOVEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
    }
}
