//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_IPDREGOUT
    {
        public long FEENO { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public Nullable<bool> CLOSEFLAG { get; set; }
        public string CLOSEREASON { get; set; }
        public Nullable<bool> DEADFLAG { get; set; }
        public string DEADREASON { get; set; }
        public Nullable<System.DateTime> DEADDATE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<int> TOTALDAY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual LTC_IPDREG LTC_IPDREG { get; set; }
    }
}
