//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PAINEVALREC
    {
        public LTC_PAINEVALREC()
        {
            this.LTC_PAINBODYPART = new HashSet<LTC_PAINBODYPART>();
        }
    
        public long SEQNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public string NEXTEVALUATEBY { get; set; }
        public string DIAGDESC { get; set; }
        public string TRANSFERPART { get; set; }
        public string COMA_E { get; set; }
        public string COMA_M { get; set; }
        public string COMA_V { get; set; }
        public string GCS { get; set; }
        public string CONSCIOUSNESS { get; set; }
        public string PAINEXPRESSION { get; set; }
        public string PAINREACTION { get; set; }
        public Nullable<bool> CANCELFLAG { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string CANCELREASON { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_PAINBODYPART> LTC_PAINBODYPART { get; set; }
    }
}
