//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ORGFLOOR
    {
        public LTC_ORGFLOOR()
        {
            this.LTC_ORGROOM = new HashSet<LTC_ORGROOM>();
        }
    
        public string FLOORID { get; set; }
        public string FLOORNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_ORGROOM> LTC_ORGROOM { get; set; }
    }
}
