//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGDISEASEHIS
    {
        public LTC_REGDISEASEHIS()
        {
            this.LTC_REGDISEASEHISDTL = new HashSet<LTC_REGDISEASEHISDTL>();
        }
    
        public int REGNO { get; set; }
        public Nullable<bool> HAVEOPERATION { get; set; }
        public string OPERATION { get; set; }
        public Nullable<bool> HAVEDRUGALLERGY { get; set; }
        public string DRUGALLERGY { get; set; }
        public Nullable<bool> HAVEFOODALLERGY { get; set; }
        public string FOODALLERGY { get; set; }
        public Nullable<bool> HAVETRANSFUSION { get; set; }
        public string ORIGMEDICALHOS { get; set; }
        public string EMERGENCYTRANSTO { get; set; }
        public Nullable<bool> ISAGREETRANSFER { get; set; }
        public string MEDICALHIS { get; set; }
        public string OTHERS { get; set; }
    
        public virtual LTC_REGFILE LTC_REGFILE { get; set; }
        public virtual ICollection<LTC_REGDISEASEHISDTL> LTC_REGDISEASEHISDTL { get; set; }
    }
}
