//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGNCIINFO
    {
        public int ID { get; set; }
        public long FEENO { get; set; }
        public string CERTNO { get; set; }
        public System.DateTime CERTSTARTTIME { get; set; }
        public System.DateTime CERTEXPIREDTIME { get; set; }
        public Nullable<System.DateTime> APPLYHOSTIME { get; set; }
        public string CARETYPEID { get; set; }
        public decimal NCIPAYLEVEL { get; set; }
        public decimal NCIPAYSCALE { get; set; }
        public int STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    }
}
