//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BEDSOREREC
    {
        public LTC_BEDSOREREC()
        {
            this.LTC_BEDSORECHGREC = new HashSet<LTC_BEDSORECHGREC>();
        }
    
        public long SEQ { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string OCCURCHANCE { get; set; }
        public Nullable<System.DateTime> OCCURDATE { get; set; }
        public string DEGREE { get; set; }
        public string EVALUTEBY { get; set; }
        public string INSPECTIONRESULT { get; set; }
        public Nullable<System.DateTime> REVOCERYDATE { get; set; }
        public string EVENTREVIEW { get; set; }
        public Nullable<bool> REVOCERYFLAG { get; set; }
        public string REVOCERYDESC { get; set; }
        public string PICT1 { get; set; }
        public string PICT2 { get; set; }
        public string PICT3 { get; set; }
        public string PICT4 { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_BEDSORECHGREC> LTC_BEDSORECHGREC { get; set; }
    }
}
