//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGQUESTION
    {
        public long RECORDID { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public Nullable<int> EVALNUMBER { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string ENVRESULTS { get; set; }
        public string DESCRIPTION { get; set; }
        public string EVALUATEBY { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public string NEXTEVALUATEBY { get; set; }
        public string NOTEVALREASON { get; set; }
        public string ORGID { get; set; }
        public string CAUSEREASON { get; set; }
        public string LASTCOMPARE { get; set; }
    }
}
