//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COSTITEM
    {
        public LTC_COSTITEM()
        {
            this.LTC_FIXEDCOST = new HashSet<LTC_FIXEDCOST>();
        }
    
        public int ID { get; set; }
        public string COSTITEMNO { get; set; }
        public string COSTNAME { get; set; }
        public string ITEMTYPE { get; set; }
        public string ITEMUNIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_FIXEDCOST> LTC_FIXEDCOST { get; set; }
    }
}
