//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NCIDEDUCTION
    {
        public int ID { get; set; }
        public string BILLID { get; set; }
        public int DEDUCTIONTYPE { get; set; }
        public string DEBITMONTH { get; set; }
        public Nullable<int> LEAVEID { get; set; }
        public Nullable<int> DEBITDAYS { get; set; }
        public double AMOUNT { get; set; }
        public string DEDUCTIONREASON { get; set; }
        public Nullable<int> DEDUCTIONSTATUS { get; set; }
        public string CREATEBY { get; set; }
        public System.DateTime CREATTIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string ORGID { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual LTC_BILLV2 LTC_BILLV2 { get; set; }
        public virtual LTC_LEAVEHOSP LTC_LEAVEHOSP { get; set; }
    }
}
