//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NUTRTIONCAREREC
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string DIETPATTERN { get; set; }
        public string NUTRTIONPATHWAY { get; set; }
        public string DIETWAY { get; set; }
        public string DINNERFREQ { get; set; }
        public string ACTIVITYABILITY { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string OTHERDISEASE { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public string WEIGHTEVAL { get; set; }
        public string DIETSTATE { get; set; }
        public Nullable<decimal> WATERUPTAKE { get; set; }
        public Nullable<int> KCAL { get; set; }
        public string KCALTYPE { get; set; }
        public Nullable<int> KCALFOOD { get; set; }
        public Nullable<int> KCALFISH { get; set; }
        public Nullable<int> KCALVEGETABLES { get; set; }
        public Nullable<int> KCALFRUIT { get; set; }
        public Nullable<int> KCALGREASE { get; set; }
        public Nullable<int> PROTEIN { get; set; }
        public string SALINITY { get; set; }
        public Nullable<int> PIPEKCAL { get; set; }
        public Nullable<int> PIPEPROTEIN { get; set; }
        public string PIPLEWATER { get; set; }
        public string PIPLEVIT { get; set; }
        public string PIPLEOTHERWATER { get; set; }
        public string NUTRTIONDIAG { get; set; }
        public string SPECIALDIET { get; set; }
        public string SUGGESTION { get; set; }
        public string DIETITIAN { get; set; }
    }
}
