//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ORGROOM
    {
        public string ROOMNO { get; set; }
        public string FLOORID { get; set; }
        public string ROOMNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string AREA { get; set; }
        public string ROOMTYPE { get; set; }
        public string ORGID { get; set; }
    
        public virtual LTC_ORGFLOOR LTC_ORGFLOOR { get; set; }
    }
}
