//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_EMPFILE
    {
        public string EMPNO { get; set; }
        public string EMPNAME { get; set; }
        public string EMPGROUP { get; set; }
        public string IDNO { get; set; }
        public Nullable<System.DateTime> BRITHDATE { get; set; }
        public string BRITHPLACE { get; set; }
        public string SEX { get; set; }
        public string BLOODTYPE { get; set; }
        public string RTHTYPE { get; set; }
        public string MERRYFLAG { get; set; }
        public string HOMETELNO { get; set; }
        public string ZIP1 { get; set; }
        public string ADDRESS1 { get; set; }
        public string ZIP2 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CONTNAME { get; set; }
        public string CONTRELATION { get; set; }
        public string CONTTELPHONE { get; set; }
        public string CONTADDRESS { get; set; }
        public string JOBTITLE { get; set; }
        public string EDUCATION { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string DEPTNO { get; set; }
        public string HIREDTYPE { get; set; }
        public string JOBTYPE { get; set; }
        public Nullable<bool> NATIVESFLAG { get; set; }
        public string LIGIOUSFAITH { get; set; }
        public Nullable<bool> DISABILITYFLAG { get; set; }
        public string NATIONALITY { get; set; }
        public string ORGID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    }
}
