//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BILLV2PAY
    {
        public LTC_BILLV2PAY()
        {
            this.LTC_BILLV2 = new HashSet<LTC_BILLV2>();
        }
    
        public int BILLPAYID { get; set; }
        public decimal SELFPAY { get; set; }
        public decimal NCIITEMTOTALCOST { get; set; }
        public decimal NCIPAY { get; set; }
        public decimal NCIITEMSELFPAY { get; set; }
        public Nullable<decimal> ACCOUNTBALANCEPAY { get; set; }
        public string OPERATOR { get; set; }
        public string PAYER { get; set; }
        public string PAYMENTTYPE { get; set; }
        public string INVOICENO { get; set; }
        public long FEENO { get; set; }
        public Nullable<System.DateTime> PAYTIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<LTC_BILLV2> LTC_BILLV2 { get; set; }
    }
}
