//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_GOODSSALE
    {
        public int Id { get; set; }
        public int GoodsId { get; set; }
        public string GoodsName { get; set; }
        public string No { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> SaleTime { get; set; }
        public string Remark { get; set; }
        public string OrgId { get; set; }
    }
}
