//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_VACCINEINJECT
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string ITEMTYPE { get; set; }
        public string STATE { get; set; }
        public string TRACESTATE { get; set; }
        public Nullable<System.DateTime> INJECTDATE { get; set; }
        public Nullable<int> INTERVALDAY { get; set; }
        public Nullable<System.DateTime> NEXTINJECTDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string NEXTOPERATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
