//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BILL
    {
        public LTC_BILL()
        {
            this.LTC_PAYBILL = new HashSet<LTC_PAYBILL>();
        }
    
        public long ID { get; set; }
        public string BILLNO { get; set; }
        public string BILLTYPE { get; set; }
        public Nullable<System.DateTime> BILLDATE { get; set; }
        public Nullable<System.DateTime> BILLENDDATE { get; set; }
        public string BILLSTATE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public int REGNO { get; set; }
        public long FEENO { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_PAYBILL> LTC_PAYBILL { get; set; }
    }
}
