//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NUTRTIONEVAL
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string SEX { get; set; }
        public string RESIDENGNO { get; set; }
        public string BEDNO { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public string DISEASEDIAG { get; set; }
        public string CHEWDIFFCULT { get; set; }
        public string SWALLOWABILITY { get; set; }
        public string EATPATTERN { get; set; }
        public string DIGESTIONPROBLEM { get; set; }
        public string FOODTABOO { get; set; }
        public string ACTIVITYABILITY { get; set; }
        public string PRESSURESORE { get; set; }
        public string EDEMA { get; set; }
        public string CURRENTDIET { get; set; }
        public string EATAMOUNT { get; set; }
        public string WATER { get; set; }
        public string SUPPLEMENTS { get; set; }
        public string SNACK { get; set; }
    }
}
