//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_UNPLANWEIGHTIND
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<decimal> THISWEIGHT { get; set; }
        public Nullable<decimal> THISHEIGHT { get; set; }
        public Nullable<decimal> WAIST { get; set; }
        public Nullable<decimal> HIPLINE { get; set; }
        public Nullable<System.DateTime> THISRECDATE { get; set; }
        public Nullable<decimal> LASTWEIGHT { get; set; }
        public Nullable<decimal> DIFFVALUE { get; set; }
        public Nullable<decimal> DIFFVALUERATE { get; set; }
        public Nullable<System.DateTime> LASTRECDATE { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public string BMIRESULTS { get; set; }
        public Nullable<decimal> B3WEIGHT { get; set; }
        public Nullable<decimal> B3DIFFVALUE { get; set; }
        public Nullable<decimal> B3DIFFVALUERATE { get; set; }
        public Nullable<decimal> B6WEIGHT { get; set; }
        public Nullable<decimal> B6DIFFVALUE { get; set; }
        public Nullable<decimal> B6DIFFVALUERATE { get; set; }
        public Nullable<bool> UNPLANFLAG { get; set; }
        public string RECORDBY { get; set; }
        public string ORGID { get; set; }
        public Nullable<decimal> KNEELEN { get; set; }
    }
}
