//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CONSTRAINSBEVAL
    {
        public long ID { get; set; }
        public Nullable<long> SEQNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public string REASON { get; set; }
        public string CONSTRAINTWAY { get; set; }
        public string BODYPART { get; set; }
        public string DURATION { get; set; }
        public string TEMPCANCELDESC { get; set; }
        public string SKINDESC { get; set; }
        public string BLOODCIRCLEDESC { get; set; }
        public string EVALUATEBY { get; set; }
    
        public virtual LTC_CONSTRAINTREC LTC_CONSTRAINTREC { get; set; }
    }
}
