//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REFERRALREC
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string UNITNAME { get; set; }
        public string UNITCONTACTOR { get; set; }
        public string UNITADDRESS { get; set; }
        public string UNITTEL { get; set; }
        public string REASON { get; set; }
        public string QUESTIONSUMMARY { get; set; }
        public string SERVICESUMMARY { get; set; }
        public string SUGGESTION { get; set; }
        public string EMPNO { get; set; }
        public Nullable<System.DateTime> REPLYDATE { get; set; }
        public string REPLYDESC { get; set; }
        public string REPLYTYPE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
