//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BEDTRANSFER
    {
        public long ID { get; set; }
        public long FEENO { get; set; }
        public string EVENTTYPE { get; set; }
        public string DEPT_O { get; set; }
        public string FLOOR_O { get; set; }
        public string ROOM_O { get; set; }
        public string BEDNO_O { get; set; }
        public string DEPT_D { get; set; }
        public string FLOOR_D { get; set; }
        public string ROOMNO_D { get; set; }
        public string BEDNO_D { get; set; }
        public Nullable<System.DateTime> TRANDATE { get; set; }
        public string TRANDESC { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
