//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PRECHARGE
    {
        public int PRECHARGEID { get; set; }
        public string BALANCEID { get; set; }
        public decimal AMOUNT { get; set; }
        public string PAYMENTTYPE { get; set; }
        public string PAYER { get; set; }
        public string RECEIPTNO { get; set; }
        public string COMMENT { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> PRECHARGETIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual LTC_RESIDENTBALANCE LTC_RESIDENTBALANCE { get; set; }
    }
}
