//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_OUTVALUE
    {
        public long OUTNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string CLASSTYPE { get; set; }
        public string OUTTYPE { get; set; }
        public Nullable<int> OUTVALUE { get; set; }
        public string COMMDESC { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
