//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PAYBILL
    {
        public long ID { get; set; }
        public long BILLID { get; set; }
        public string PAYBILLNO { get; set; }
        public Nullable<System.DateTime> PAYBILLTIME { get; set; }
        public string PAYOR { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string INVOICENO { get; set; }
        public string ACCOUNTANTCODE { get; set; }
        public string RECRODBY { get; set; }
        public Nullable<decimal> SUMMARY { get; set; }
        public Nullable<decimal> RECEIVED { get; set; }
        public string BILLSTATUS { get; set; }
    
        public virtual LTC_BILL LTC_BILL { get; set; }
    }
}
