//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_MAKERITEMLIMITEDVALUE
    {
        public int LIMITEDVALUEID { get; set; }
        public Nullable<decimal> LIMITEDVALUE { get; set; }
        public string LIMITEDVALUENAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public Nullable<bool> ISDEFAULT { get; set; }
        public int LIMITEDID { get; set; }
    }
}
