//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NCIEVALUATEDTL
    {
        public int ID { get; set; }
        public Nullable<int> NCIEVALUATEID { get; set; }
        public string ITEMCODE { get; set; }
        public Nullable<int> SUBITEMID { get; set; }
        public Nullable<int> SCORE { get; set; }
    
        public virtual LTC_NCIEVALUATE LTC_NCIEVALUATE { get; set; }
    }
}
