//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NEWRESIDENTENVREC
    {
        public long ID { get; set; }
        public string RESIDENGNO { get; set; }
        public string BEDNO { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<bool> FAMILYPARTICIPATION { get; set; }
        public Nullable<bool> CONTRACTFLAG { get; set; }
        public Nullable<bool> LIFEFLAG { get; set; }
        public string STAFF1 { get; set; }
        public Nullable<bool> REGULARACTIVITY { get; set; }
        public Nullable<bool> NOTREGULARACTIVITY { get; set; }
        public string STAFF2 { get; set; }
        public Nullable<bool> BELLFLAG { get; set; }
        public Nullable<bool> LAMPFLAG { get; set; }
        public Nullable<bool> TVFLAG { get; set; }
        public Nullable<bool> LIGHTSWITCH { get; set; }
        public Nullable<bool> ESCAPEDEVICE { get; set; }
        public Nullable<bool> ENVIRONMENT { get; set; }
        public Nullable<bool> COMMUNITYFACILITIES { get; set; }
        public Nullable<bool> POSTOFFICE { get; set; }
        public Nullable<bool> SCHOOL { get; set; }
        public Nullable<bool> BANK { get; set; }
        public Nullable<bool> STATION { get; set; }
        public Nullable<bool> PARK { get; set; }
        public Nullable<bool> TEMPLE { get; set; }
        public Nullable<bool> HOSPITAL { get; set; }
        public Nullable<bool> OTHERFACILITIES { get; set; }
        public Nullable<bool> CLEANLINESS { get; set; }
        public Nullable<bool> MEDICALCARE { get; set; }
        public Nullable<bool> MEALSERVICE { get; set; }
        public Nullable<bool> WORKACTIVITIES { get; set; }
        public string STAFF3 { get; set; }
        public string STAFF4 { get; set; }
        public Nullable<bool> PERSONINCHARGE { get; set; }
        public Nullable<bool> DIRECTOR { get; set; }
        public Nullable<bool> NURSE { get; set; }
        public Nullable<bool> NURSEAIDES { get; set; }
        public Nullable<bool> RESIDENT { get; set; }
        public Nullable<bool> DOCTOR { get; set; }
        public Nullable<bool> SOCIALWORKER { get; set; }
        public Nullable<bool> DIETITIAN { get; set; }
        public Nullable<bool> OTHERPEOPLE { get; set; }
        public string STAFF5 { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string ORGID { get; set; }
    }
}
