//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGRELATION
    {
        public long FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string ZIP1 { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS1DTL { get; set; }
        public string ZIP2 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS2DTL { get; set; }
        public Nullable<bool> HOUSEHOLDFLAG { get; set; }
        public string CONTACTPHONE { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
        public string PHOTOPATH { get; set; }
        public string FAMILYPATH { get; set; }
        public string CITY1 { get; set; }
        public string CITY2 { get; set; }
        public string PAYMENTPERSON { get; set; }
        public string KINSHIP { get; set; }
        public string BILLADDRESS { get; set; }
    }
}
