//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_FEERECORD
    {
        public string FEERECORDID { get; set; }
        public string BILLID { get; set; }
        public int CHARGERECORDTYPE { get; set; }
        public int CHARGERECORDID { get; set; }
        public long FEENO { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal COUNT { get; set; }
        public decimal COST { get; set; }
        public bool ISNCIITEM { get; set; }
        public bool ISREFUNDRECORD { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual LTC_BILLV2 LTC_BILLV2 { get; set; }
    }
}
