//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_GROUPACTIVITYREC
    {
        public int ID { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string ACTIVITYTYPE { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public Nullable<int> EVENTHOURS { get; set; }
        public string EVENTPLACE { get; set; }
        public string LEADERNAME { get; set; }
        public string LEADERNAME1 { get; set; }
        public string LEADERNAME2 { get; set; }
        public string ACTIVITYRESULTS { get; set; }
        public Nullable<int> EVALRESULTS { get; set; }
        public Nullable<int> ATTENDNUMBER { get; set; }
        public string GROUPCOMPETENCE { get; set; }
        public string INDIVIDUALSUMMARY { get; set; }
        public string SUGGESTION { get; set; }
        public string DESCRIPTION { get; set; }
        public string PICTURE1 { get; set; }
        public string PICTURE2 { get; set; }
        public string ATTENDNO { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
