//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PROPOSALDISSCUSSREC
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> MEETINGDATE { get; set; }
        public string RECORDBY { get; set; }
        public string MEETCHAIRMAN { get; set; }
        public string ATTENDANCE { get; set; }
        public string GUIDTEACHER { get; set; }
        public string MEETINGADDRESS { get; set; }
        public string MEETINGTITLE { get; set; }
        public string QUESTION { get; set; }
        public string QUESTIONDIAG { get; set; }
        public string TEACHERSUGGESTION { get; set; }
        public string QUESTIONDISSCUSSION { get; set; }
        public string DECISIONS { get; set; }
        public string MOTION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<long> RECORDID { get; set; }
    
        public virtual LTC_PROPOSALDISSCUSS LTC_PROPOSALDISSCUSS { get; set; }
    }
}
