//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGINSDTL
    {
        public long FEENO { get; set; }
        public string SOURCETYPE { get; set; }
        public string INSTYPE { get; set; }
        public string INREASON { get; set; }
        public string INTYPE { get; set; }
        public string ECONOMYFLAG { get; set; }
        public string CASETYPE { get; set; }
        public string HOSPFILE { get; set; }
        public string INSMARK { get; set; }
        public Nullable<bool> CUSTODYFLAG { get; set; }
        public Nullable<bool> ASSISTFLAG { get; set; }
        public Nullable<System.DateTime> LPAPPDATE { get; set; }
        public Nullable<System.DateTime> LPCHECKDATE { get; set; }
        public string APPDOCNO { get; set; }
        public string ILLFLAG { get; set; }
        public string CERTIFYNO { get; set; }
        public Nullable<bool> NEEDCERTIFY { get; set; }
        public Nullable<System.DateTime> CERTIFYDATE { get; set; }
        public Nullable<bool> BOOKFLAG { get; set; }
        public string BOOKNO { get; set; }
        public Nullable<System.DateTime> BOOKISSUEDATE { get; set; }
        public Nullable<System.DateTime> BOOKEXPDATE { get; set; }
        public string BOOKTYPE { get; set; }
        public string DISABDEGREE { get; set; }
        public string IQ { get; set; }
        public string DISABCAUSE { get; set; }
        public string DISABTYPEDTL { get; set; }
        public string DISABCHECKDESC { get; set; }
        public string PROCDOC { get; set; }
        public Nullable<bool> INSFLAG { get; set; }
        public string INSURANCEDESC { get; set; }
        public string DOCLACKDESC { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
        public string PTYPE { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> DISABILITYEXPDATE { get; set; }
        public string DISABILITYGRADE { get; set; }
        public Nullable<System.DateTime> DISABILITYEVALDATE { get; set; }
        public Nullable<bool> ISREEVAL { get; set; }
        public Nullable<System.DateTime> DISABILITYREEVALDATE { get; set; }
        public Nullable<bool> ISHOUSEMIGRATION1 { get; set; }
        public Nullable<bool> ISHOUSEMIGRATION2 { get; set; }
        public Nullable<System.DateTime> INMIGRATIONDATE1 { get; set; }
        public Nullable<System.DateTime> INMIGRATIONDATE2 { get; set; }
        public Nullable<bool> DISABILITYCATE1 { get; set; }
        public Nullable<bool> DISABILITYCATE2 { get; set; }
        public Nullable<bool> DISABILITYCATE3 { get; set; }
        public Nullable<bool> DISABILITYCATE4 { get; set; }
        public Nullable<bool> DISABILITYCATE5 { get; set; }
        public Nullable<bool> DISABILITYCATE6 { get; set; }
        public Nullable<bool> DISABILITYCATE7 { get; set; }
        public Nullable<bool> DISABILITYCATE8 { get; set; }
        public string ICFCODE1 { get; set; }
        public string ICFCODE2 { get; set; }
        public string ICFCODE3 { get; set; }
        public string ICFCODE4 { get; set; }
        public string ICFCODE5 { get; set; }
        public string ICFCODE6 { get; set; }
        public string ICFCODE7 { get; set; }
        public string ICFCODE8 { get; set; }
        public string ICDDIAGNOSI { get; set; }
    }
}
