//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_MAKERITEM
    {
        public int MAKERID { get; set; }
        public string MAKENAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public Nullable<bool> ISSHOW { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<int> LIMITEDID { get; set; }
        public string CATEGORY { get; set; }
    }
}
