//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGEVALUATE
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public Nullable<int> COUNT { get; set; }
        public string EVALUATEBY { get; set; }
        public string NEXTEVALUATEBY { get; set; }
        public string AIDTOOLS { get; set; }
        public string BOOKTYPE { get; set; }
        public string BOOKDEGREE { get; set; }
        public string ILLCARDNAME { get; set; }
        public string SERVICENAME { get; set; }
        public string MINDSTATE { get; set; }
        public string COGNITIVESTATE { get; set; }
        public string EXPRESSIONSTATE { get; set; }
        public string NONEXPRESSIONSTATE { get; set; }
        public string LANGUAGESTATE { get; set; }
        public string EMOTIONSTATE { get; set; }
        public string PERSONALITY { get; set; }
        public string ATTENTION { get; set; }
        public string REALISTICSENSE { get; set; }
        public string SOCIALPARTICIPATION { get; set; }
        public string SOCIALATTITUDE { get; set; }
        public string SOCIALSKILLS { get; set; }
        public string COMMSKILLS { get; set; }
        public string RESPONSESKILLS { get; set; }
        public string FIXISSUESKILLS { get; set; }
        public string HOBBY { get; set; }
        public string EXPERTISE { get; set; }
        public string SPECIALBEHAVIOR { get; set; }
        public string ADMISSIONREASON { get; set; }
        public string MEDICALHISTORY { get; set; }
        public string PSYCHOLOGYDESC { get; set; }
        public string FAMILYSUBSYSTEM { get; set; }
        public string SOCIALRELATIONSHIP { get; set; }
        public string KEYQUESTION { get; set; }
        public string PROCESSPLAN_S { get; set; }
        public string RELATIVESDISCUSS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> VERIFYDATE { get; set; }
        public string VERIFYBY { get; set; }
        public string FAMILYFUNROLE { get; set; }
        public string FAMILYSUPPORT { get; set; }
        public string FAMILYFINANCIAL { get; set; }
        public string SOCIALSUPPORT { get; set; }
        public string SOCIALFORMALRESOURCE { get; set; }
        public string PROCESSPLAN_M { get; set; }
        public string PROCESSPLAN_L { get; set; }
        public string ORGID { get; set; }
    }
}
