//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COSTDTL
    {
        public long ID { get; set; }
        public string COSTNO { get; set; }
        public string COSTITEMNO { get; set; }
        public string COSTNAME { get; set; }
        public Nullable<int> COSTSOURCE { get; set; }
        public string ITEMTYPE { get; set; }
        public Nullable<System.DateTime> OCCURTIME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> TOTALPRICE { get; set; }
        public Nullable<bool> SELFFLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public int REGNO { get; set; }
        public long FEENO { get; set; }
        public string ORGID { get; set; }
        public Nullable<long> BILLID { get; set; }
    }
}
