//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CAREDEMANDEVAL
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public string NEXTEVALUATEBY { get; set; }
        public Nullable<int> COUNT { get; set; }
        public string EVALUATEBY { get; set; }
        public Nullable<bool> HEALTHFLAG { get; set; }
        public string HEALTHDESC { get; set; }
        public Nullable<bool> INFECTIONFLAG { get; set; }
        public string INFECTIONDESC { get; set; }
        public Nullable<bool> VITALSIGNFLAG { get; set; }
        public Nullable<decimal> BODYTEMP { get; set; }
        public Nullable<int> PULSE { get; set; }
        public Nullable<int> BREATHE { get; set; }
        public Nullable<int> SBP { get; set; }
        public Nullable<int> DBP { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string CONSCIOUSNESS { get; set; }
        public string CONSCIOUSNESS_E { get; set; }
        public string CONSCIOUSNESS_V { get; set; }
        public string CONSCIOUSNESS_M { get; set; }
        public Nullable<bool> APPEARANCEFLAG { get; set; }
        public string APPEARANCEDESC { get; set; }
        public string ATTITUDE { get; set; }
        public Nullable<bool> BREATHPROBLEMFLAG { get; set; }
        public string BREATEDESC { get; set; }
        public string SECRETIONDESC { get; set; }
        public string SECRETIONNATURE { get; set; }
        public string SECRETIONAMT { get; set; }
        public string COUGHDESC { get; set; }
        public string BREATHAIDTOOLS { get; set; }
        public string SMOKINGHISTORY { get; set; }
        public Nullable<bool> NUTRITIONFLAG { get; set; }
        public string EATTYPE { get; set; }
        public string DIETTYPEDESC { get; set; }
        public string FOODINTAKEAMT { get; set; }
        public string WATERAMT { get; set; }
        public string WATERENOUGHAMT { get; set; }
        public string ORALMUCOSA { get; set; }
        public string DENTUREFIXED { get; set; }
        public string DENTUREMOVABLE { get; set; }
        public string DENTURESAFETY { get; set; }
        public string DENTUREFIT { get; set; }
        public string DENTUREHEALTH { get; set; }
        public Nullable<bool> EXCRETIONFLAG { get; set; }
        public string MICTURITIONDESC { get; set; }
        public string MICTURITIONAIDTYPE { get; set; }
        public string DEFECATIONDESC { get; set; }
        public string DEFECATIONFREQ { get; set; }
        public string DEFECATIONAIDDESC { get; set; }
        public string OTHERDEFECATION { get; set; }
        public Nullable<bool> SLEEPFLAG { get; set; }
        public Nullable<decimal> SLEEPHOURS_N { get; set; }
        public Nullable<decimal> SLEEPHOURS_D { get; set; }
        public string SLEEPDESC { get; set; }
        public string SLEEPPILLS { get; set; }
        public Nullable<bool> ACTIVEFUNFLAG { get; set; }
        public string GAIT { get; set; }
        public string PHYSICALIMPAIRMENT { get; set; }
        public string MUSCLE_LH { get; set; }
        public string MUSCLE_RH { get; set; }
        public string MUSCLE_LF { get; set; }
        public string MUSCLE_RF { get; set; }
        public string AIDTOOLS { get; set; }
        public Nullable<bool> SKINFLAG { get; set; }
        public string SKINDESC { get; set; }
        public string SKINPARTDESC { get; set; }
        public string WOUNDDESC { get; set; }
        public string BEDSOREPART { get; set; }
        public string BEDSORESIZE { get; set; }
        public string BEDSOREDEGREE { get; set; }
        public Nullable<bool> FEELINGFLAG { get; set; }
        public string SIGHTDESC { get; set; }
        public string SIGHT_L { get; set; }
        public string SIGHT_R { get; set; }
        public string LISTENDESC { get; set; }
        public string LISTEN_L { get; set; }
        public string LISTEN_R { get; set; }
        public string SENSATIONDESC { get; set; }
        public string PAINDESC { get; set; }
        public string PAINPART { get; set; }
        public string PAIN_FREQ { get; set; }
        public string PAIN_NUTURE { get; set; }
        public string PAIN_SHOW { get; set; }
        public string PAINDRUGDESC { get; set; }
        public string ILLUSIONDESC { get; set; }
        public Nullable<int> ADLSCORE { get; set; }
        public Nullable<int> MMSESCORE { get; set; }
        public string MMSEDESC { get; set; }
        public Nullable<bool> INTERACTIONFLAG { get; set; }
        public string COMMUNICATESKILL { get; set; }
        public string COMMUNICATETYPE { get; set; }
        public string COMMUNICATEDESC { get; set; }
        public string APPELLATION { get; set; }
        public string EMOTION { get; set; }
        public string ATTITUDEREMARK { get; set; }
        public Nullable<bool> ALLERGYFLAG { get; set; }
        public string ALLERGY_DRUG { get; set; }
        public string ALLERGY_FOOD { get; set; }
        public string ALLERGY_OTHERS { get; set; }
        public string GOAL_S { get; set; }
        public string GOAL_L { get; set; }
        public string DESCRIPTION { get; set; }
        public string PIC1 { get; set; }
        public string PIC2 { get; set; }
        public string ADLRESULTS { get; set; }
        public string iADLRESULTS { get; set; }
        public string KS_RESULTS { get; set; }
        public string YY_RESULTS { get; set; }
        public string FALLRESULTS { get; set; }
        public string PRESSURESORE { get; set; }
        public string MUSCLETYPE_LH { get; set; }
        public string MUSCLETYPE_RH { get; set; }
        public string MUSCLETYPE_LF { get; set; }
        public string MUSCLETYPE_RF { get; set; }
        public string JOINTTYPE_LH { get; set; }
        public string JOINTTYPE_RH { get; set; }
        public string JOINTTYPE_LF { get; set; }
        public string JOINTTYPE_RF { get; set; }
        public string GCSRESULTS { get; set; }
        public string PAINDEGREEDESC_W { get; set; }
        public string ACCIDENT_W { get; set; }
        public string ABNORMAL_W { get; set; }
        public string HEARINGAID { get; set; }
        public string SIGHTCORRECTED { get; set; }
        public string BALANCE_SIT { get; set; }
        public string BALANCE_STAND { get; set; }
        public string BALANCE_WALK { get; set; }
        public string URINESHAPE { get; set; }
        public string GUT_SOUND { get; set; }
        public string GUT_FLATULENCE { get; set; }
        public string GUT_LUMP { get; set; }
        public string STOOLSHAPE { get; set; }
        public string MOUTHPAIN { get; set; }
        public string TOOTHDESC { get; set; }
        public string SWALLOWDESC { get; set; }
        public string LIGHTREFLECTION { get; set; }
        public string HEARTBEAT { get; set; }
        public string LIMBEDEMA_LH { get; set; }
        public string LIMBEDEMA_RH { get; set; }
        public string LIMBEDEMA_LF { get; set; }
        public string LIMBEDEMA_RF { get; set; }
        public string CARENEEDS { get; set; }
        public string CAREQUESTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
