//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NSSERVICE
    {
        public LTC_NSSERVICE()
        {
            this.LTC_SERVICERECORD = new HashSet<LTC_SERVICERECORD>();
        }
    
        public int SERVICEID { get; set; }
        public string ACCOUNTINGID { get; set; }
        public string CHARGETYPEID { get; set; }
        public string NSID { get; set; }
        public bool ISNCIITEM { get; set; }
        public string MCSERVICECODE { get; set; }
        public string NSSERVICECODE { get; set; }
        public string MCRULEID { get; set; }
        public string SERVICENAME { get; set; }
        public string SERVICEDESC { get; set; }
        public string UNITS { get; set; }
        public decimal UNITPRICE { get; set; }
        public Nullable<decimal> GUIDEPRICE { get; set; }
        public Nullable<decimal> MAXPRICE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public string PINYIN { get; set; }
        public int STATUS { get; set; }
        public bool ISREQUIREUPDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<LTC_SERVICERECORD> LTC_SERVICERECORD { get; set; }
    }
}
