//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NOTIFICATION
    {
        public int ID { get; set; }
        public string SUBJECTS { get; set; }
        public string CONTENTS { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCUMENTNO { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<System.DateTime> EXPRIEDATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
