//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TWSLTCEntities : DbContext
    {
        public TWSLTCEntities()
            : base("name=TWSLTCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARE_PLANACTIVITY> CARE_PLANACTIVITY { get; set; }
        public virtual DbSet<CARE_PLANCHECKPOINT> CARE_PLANCHECKPOINT { get; set; }
        public virtual DbSet<CARE_PLANDATA> CARE_PLANDATA { get; set; }
        public virtual DbSet<CARE_PLANEVAL> CARE_PLANEVAL { get; set; }
        public virtual DbSet<CARE_PLANFOCUS> CARE_PLANFOCUS { get; set; }
        public virtual DbSet<CARE_PLANGOAL> CARE_PLANGOAL { get; set; }
        public virtual DbSet<CARE_PLANPROBLEM> CARE_PLANPROBLEM { get; set; }
        public virtual DbSet<CARE_PLANREASON> CARE_PLANREASON { get; set; }
        public virtual DbSet<CARE_PLANTRAIN> CARE_PLANTRAIN { get; set; }
        public virtual DbSet<CHECKITEM> CHECKITEM { get; set; }
        public virtual DbSet<CHECKTEMPLATE> CHECKTEMPLATE { get; set; }
        public virtual DbSet<CHECKTEMPLATEITEM> CHECKTEMPLATEITEM { get; set; }
        public virtual DbSet<DC_ABNORMALEMOTIONREC> DC_ABNORMALEMOTIONREC { get; set; }
        public virtual DbSet<DC_ASSESSVALUE> DC_ASSESSVALUE { get; set; }
        public virtual DbSet<DC_CAREPLANACTIVITY> DC_CAREPLANACTIVITY { get; set; }
        public virtual DbSet<DC_CAREPLANDATA> DC_CAREPLANDATA { get; set; }
        public virtual DbSet<DC_CAREPLANEVAL> DC_CAREPLANEVAL { get; set; }
        public virtual DbSet<DC_CAREPLANGOAL> DC_CAREPLANGOAL { get; set; }
        public virtual DbSet<DC_CAREPLANPROBLEM> DC_CAREPLANPROBLEM { get; set; }
        public virtual DbSet<DC_CAREPLANREASON> DC_CAREPLANREASON { get; set; }
        public virtual DbSet<DC_COMMDTL> DC_COMMDTL { get; set; }
        public virtual DbSet<DC_COMMFILE> DC_COMMFILE { get; set; }
        public virtual DbSet<DC_DAYLIFECAREDTL> DC_DAYLIFECAREDTL { get; set; }
        public virtual DbSet<DC_DAYLIFECAREREC> DC_DAYLIFECAREREC { get; set; }
        public virtual DbSet<DC_EVALQUESTION> DC_EVALQUESTION { get; set; }
        public virtual DbSet<DC_EVALQUESTIONRESULT> DC_EVALQUESTIONRESULT { get; set; }
        public virtual DbSet<DC_IPDREG> DC_IPDREG { get; set; }
        public virtual DbSet<DC_LIFEHISTORY> DC_LIFEHISTORY { get; set; }
        public virtual DbSet<DC_MULTITEAMCAREPLAN> DC_MULTITEAMCAREPLAN { get; set; }
        public virtual DbSet<DC_MULTITEAMCAREPLANEVAL> DC_MULTITEAMCAREPLANEVAL { get; set; }
        public virtual DbSet<DC_MULTITEAMCAREPLANREC> DC_MULTITEAMCAREPLANREC { get; set; }
        public virtual DbSet<DC_NOTE> DC_NOTE { get; set; }
        public virtual DbSet<DC_NSCPLACTIVITY> DC_NSCPLACTIVITY { get; set; }
        public virtual DbSet<DC_NSCPLGOAL> DC_NSCPLGOAL { get; set; }
        public virtual DbSet<DC_NURSEINGLIFECAREDTL> DC_NURSEINGLIFECAREDTL { get; set; }
        public virtual DbSet<DC_NURSEINGLIFECAREREC> DC_NURSEINGLIFECAREREC { get; set; }
        public virtual DbSet<DC_NURSEINGPLANEVAL> DC_NURSEINGPLANEVAL { get; set; }
        public virtual DbSet<DC_QUESTION> DC_QUESTION { get; set; }
        public virtual DbSet<DC_QUESTIONITEM> DC_QUESTIONITEM { get; set; }
        public virtual DbSet<DC_QUESTIONVALUE> DC_QUESTIONVALUE { get; set; }
        public virtual DbSet<DC_REFERRALLISTS> DC_REFERRALLISTS { get; set; }
        public virtual DbSet<DC_REGACTIVITYREQUESTEVAL> DC_REGACTIVITYREQUESTEVAL { get; set; }
        public virtual DbSet<DC_REGBASEINFOLIST> DC_REGBASEINFOLIST { get; set; }
        public virtual DbSet<DC_REGCASECAREPLAN> DC_REGCASECAREPLAN { get; set; }
        public virtual DbSet<DC_REGCASECAREPLANREC> DC_REGCASECAREPLANREC { get; set; }
        public virtual DbSet<DC_REGCHECKRECORD> DC_REGCHECKRECORD { get; set; }
        public virtual DbSet<DC_REGCHECKRECORDDATA> DC_REGCHECKRECORDDATA { get; set; }
        public virtual DbSet<DC_REGCPL> DC_REGCPL { get; set; }
        public virtual DbSet<DC_REGDAYLIFE> DC_REGDAYLIFE { get; set; }
        public virtual DbSet<DC_REGEVALQUESTION> DC_REGEVALQUESTION { get; set; }
        public virtual DbSet<DC_REGFILE> DC_REGFILE { get; set; }
        public virtual DbSet<DC_REGLIFEQUALITYEVAL> DC_REGLIFEQUALITYEVAL { get; set; }
        public virtual DbSet<DC_REGMEDICINE> DC_REGMEDICINE { get; set; }
        public virtual DbSet<DC_REGNOTERECORD> DC_REGNOTERECORD { get; set; }
        public virtual DbSet<DC_REGNURSINGDIAG> DC_REGNURSINGDIAG { get; set; }
        public virtual DbSet<DC_REGQUESTIONDATA> DC_REGQUESTIONDATA { get; set; }
        public virtual DbSet<DC_REGQUESTIONEVALREC> DC_REGQUESTIONEVALREC { get; set; }
        public virtual DbSet<DC_REGVISITRECORD> DC_REGVISITRECORD { get; set; }
        public virtual DbSet<DC_SWREGEVALPLAN> DC_SWREGEVALPLAN { get; set; }
        public virtual DbSet<DC_TASKGOALSSTRATEGY> DC_TASKGOALSSTRATEGY { get; set; }
        public virtual DbSet<DC_TASKREMIND> DC_TASKREMIND { get; set; }
        public virtual DbSet<DC_TEAMACTIVITY> DC_TEAMACTIVITY { get; set; }
        public virtual DbSet<DC_TEAMACTIVITYDTL> DC_TEAMACTIVITYDTL { get; set; }
        public virtual DbSet<LTC_ACTIVEPERIOD> LTC_ACTIVEPERIOD { get; set; }
        public virtual DbSet<LTC_ACTIVEPERIOD_HIST> LTC_ACTIVEPERIOD_HIST { get; set; }
        public virtual DbSet<LTC_AFFAIRSHANDOVER> LTC_AFFAIRSHANDOVER { get; set; }
        public virtual DbSet<LTC_ASSESSVALUE> LTC_ASSESSVALUE { get; set; }
        public virtual DbSet<LTC_ASSIGNTASK> LTC_ASSIGNTASK { get; set; }
        public virtual DbSet<LTC_BEDBASIC> LTC_BEDBASIC { get; set; }
        public virtual DbSet<LTC_BEDSORECHGREC> LTC_BEDSORECHGREC { get; set; }
        public virtual DbSet<LTC_BEDSOREREC> LTC_BEDSOREREC { get; set; }
        public virtual DbSet<LTC_BEDTRANSFER> LTC_BEDTRANSFER { get; set; }
        public virtual DbSet<LTC_BILL> LTC_BILL { get; set; }
        public virtual DbSet<LTC_BILLV2> LTC_BILLV2 { get; set; }
        public virtual DbSet<LTC_BILLV2PAY> LTC_BILLV2PAY { get; set; }
        public virtual DbSet<LTC_CAREDEMANDEVAL> LTC_CAREDEMANDEVAL { get; set; }
        public virtual DbSet<LTC_CARERSVRREC> LTC_CARERSVRREC { get; set; }
        public virtual DbSet<LTC_CHARGEGROUP> LTC_CHARGEGROUP { get; set; }
        public virtual DbSet<LTC_CHARGEGROUP_CHARGEITEM> LTC_CHARGEGROUP_CHARGEITEM { get; set; }
        public virtual DbSet<LTC_CHARGEGROUP_CHARGERECORD> LTC_CHARGEGROUP_CHARGERECORD { get; set; }
        public virtual DbSet<LTC_CHARGEGROUP_RESIDENT> LTC_CHARGEGROUP_RESIDENT { get; set; }
        public virtual DbSet<LTC_CHECKGROUP> LTC_CHECKGROUP { get; set; }
        public virtual DbSet<LTC_CHECKITEM> LTC_CHECKITEM { get; set; }
        public virtual DbSet<LTC_CHECKREC> LTC_CHECKREC { get; set; }
        public virtual DbSet<LTC_CHECKRECDTL> LTC_CHECKRECDTL { get; set; }
        public virtual DbSet<LTC_CHECKTYPE> LTC_CHECKTYPE { get; set; }
        public virtual DbSet<LTC_CODEDTL_REF> LTC_CODEDTL_REF { get; set; }
        public virtual DbSet<LTC_CODEFILE_REF> LTC_CODEFILE_REF { get; set; }
        public virtual DbSet<LTC_COMMFILE> LTC_COMMFILE { get; set; }
        public virtual DbSet<LTC_COMPLAINREC> LTC_COMPLAINREC { get; set; }
        public virtual DbSet<LTC_CONSTRAINSBEVAL> LTC_CONSTRAINSBEVAL { get; set; }
        public virtual DbSet<LTC_CONSTRAINTREC> LTC_CONSTRAINTREC { get; set; }
        public virtual DbSet<LTC_CONSULTCALLBACK> LTC_CONSULTCALLBACK { get; set; }
        public virtual DbSet<LTC_CONSULTREC> LTC_CONSULTREC { get; set; }
        public virtual DbSet<LTC_COSTDTL> LTC_COSTDTL { get; set; }
        public virtual DbSet<LTC_COSTGROUP> LTC_COSTGROUP { get; set; }
        public virtual DbSet<LTC_COSTGROUPDTL> LTC_COSTGROUPDTL { get; set; }
        public virtual DbSet<LTC_COSTITEM> LTC_COSTITEM { get; set; }
        public virtual DbSet<LTC_DEPTFILE> LTC_DEPTFILE { get; set; }
        public virtual DbSet<LTC_DOCTORCHECKREC> LTC_DOCTORCHECKREC { get; set; }
        public virtual DbSet<LTC_DOCTOREVALREC> LTC_DOCTOREVALREC { get; set; }
        public virtual DbSet<LTC_DRGFREQREF> LTC_DRGFREQREF { get; set; }
        public virtual DbSet<LTC_DRUGRECORD> LTC_DRUGRECORD { get; set; }
        public virtual DbSet<LTC_EMPFILE> LTC_EMPFILE { get; set; }
        public virtual DbSet<LTC_FALLINCIDENTEVENT> LTC_FALLINCIDENTEVENT { get; set; }
        public virtual DbSet<LTC_FAMILYDISCUSSREC> LTC_FAMILYDISCUSSREC { get; set; }
        public virtual DbSet<LTC_FEERECORD> LTC_FEERECORD { get; set; }
        public virtual DbSet<LTC_FIXEDCOST> LTC_FIXEDCOST { get; set; }
        public virtual DbSet<LTC_FSTREGREC> LTC_FSTREGREC { get; set; }
        public virtual DbSet<LTC_GOODS> LTC_GOODS { get; set; }
        public virtual DbSet<LTC_GOODSLOAN> LTC_GOODSLOAN { get; set; }
        public virtual DbSet<LTC_GOODSSALE> LTC_GOODSSALE { get; set; }
        public virtual DbSet<LTC_GROUP> LTC_GROUP { get; set; }
        public virtual DbSet<LTC_GROUPACTIVITYREC> LTC_GROUPACTIVITYREC { get; set; }
        public virtual DbSet<LTC_HANDOVERDTL> LTC_HANDOVERDTL { get; set; }
        public virtual DbSet<LTC_HANDOVERRECORD> LTC_HANDOVERRECORD { get; set; }
        public virtual DbSet<LTC_HOMECARESUPERVISE> LTC_HOMECARESUPERVISE { get; set; }
        public virtual DbSet<LTC_HOMECARESVRREC> LTC_HOMECARESVRREC { get; set; }
        public virtual DbSet<LTC_ICD9_DISEASE> LTC_ICD9_DISEASE { get; set; }
        public virtual DbSet<LTC_INFECTIONIND> LTC_INFECTIONIND { get; set; }
        public virtual DbSet<LTC_INFECTIONITEM> LTC_INFECTIONITEM { get; set; }
        public virtual DbSet<LTC_INFECTIONSYMPOTM> LTC_INFECTIONSYMPOTM { get; set; }
        public virtual DbSet<LTC_INSULININJECT> LTC_INSULININJECT { get; set; }
        public virtual DbSet<LTC_INVALUE> LTC_INVALUE { get; set; }
        public virtual DbSet<LTC_IPDCLOSECASE> LTC_IPDCLOSECASE { get; set; }
        public virtual DbSet<LTC_IPDORDER> LTC_IPDORDER { get; set; }
        public virtual DbSet<LTC_IPDORDERPOSTREC> LTC_IPDORDERPOSTREC { get; set; }
        public virtual DbSet<LTC_IPDREG> LTC_IPDREG { get; set; }
        public virtual DbSet<LTC_IPDREGOUT> LTC_IPDREGOUT { get; set; }
        public virtual DbSet<LTC_IPDVERIFY> LTC_IPDVERIFY { get; set; }
        public virtual DbSet<LTC_LABEXAMREC> LTC_LABEXAMREC { get; set; }
        public virtual DbSet<LTC_LEAVEHOSP> LTC_LEAVEHOSP { get; set; }
        public virtual DbSet<LTC_LIFERECORDS> LTC_LIFERECORDS { get; set; }
        public virtual DbSet<LTC_LOG> LTC_LOG { get; set; }
        public virtual DbSet<LTC_LOOKOVER> LTC_LOOKOVER { get; set; }
        public virtual DbSet<LTC_MAKERITEM> LTC_MAKERITEM { get; set; }
        public virtual DbSet<LTC_MAKERITEMLIMITED> LTC_MAKERITEMLIMITED { get; set; }
        public virtual DbSet<LTC_MAKERITEMLIMITEDVALUE> LTC_MAKERITEMLIMITEDVALUE { get; set; }
        public virtual DbSet<LTC_MANUFACTURE> LTC_MANUFACTURE { get; set; }
        public virtual DbSet<LTC_MATERIALRECORD> LTC_MATERIALRECORD { get; set; }
        public virtual DbSet<LTC_MATHNUMBER> LTC_MATHNUMBER { get; set; }
        public virtual DbSet<LTC_MEASUREDRECORD> LTC_MEASUREDRECORD { get; set; }
        public virtual DbSet<LTC_MEASUREITEM> LTC_MEASUREITEM { get; set; }
        public virtual DbSet<LTC_MEDICINE> LTC_MEDICINE { get; set; }
        public virtual DbSet<LTC_MODULES> LTC_MODULES { get; set; }
        public virtual DbSet<LTC_MONTHLYPAYBILLRECORD> LTC_MONTHLYPAYBILLRECORD { get; set; }
        public virtual DbSet<LTC_MONTHLYPAYLIMIT> LTC_MONTHLYPAYLIMIT { get; set; }
        public virtual DbSet<LTC_NCIDEDUCTION> LTC_NCIDEDUCTION { get; set; }
        public virtual DbSet<LTC_NCIEVALUATE> LTC_NCIEVALUATE { get; set; }
        public virtual DbSet<LTC_NCIEVALUATEDTL> LTC_NCIEVALUATEDTL { get; set; }
        public virtual DbSet<LTC_NCIFINANCIALMONTH> LTC_NCIFINANCIALMONTH { get; set; }
        public virtual DbSet<LTC_NCISUPERVISE> LTC_NCISUPERVISE { get; set; }
        public virtual DbSet<LTC_NEWREGENVADAPTATION> LTC_NEWREGENVADAPTATION { get; set; }
        public virtual DbSet<LTC_NEWRESIDENTENVREC> LTC_NEWRESIDENTENVREC { get; set; }
        public virtual DbSet<LTC_NOTIFICATION> LTC_NOTIFICATION { get; set; }
        public virtual DbSet<LTC_NSCPL> LTC_NSCPL { get; set; }
        public virtual DbSet<LTC_NSCPLACTIVITY> LTC_NSCPLACTIVITY { get; set; }
        public virtual DbSet<LTC_NSCPLGOAL> LTC_NSCPLGOAL { get; set; }
        public virtual DbSet<LTC_NSDRUG> LTC_NSDRUG { get; set; }
        public virtual DbSet<LTC_NSMEDICALMATERIAL> LTC_NSMEDICALMATERIAL { get; set; }
        public virtual DbSet<LTC_NSSERVICE> LTC_NSSERVICE { get; set; }
        public virtual DbSet<LTC_NURSERPTTPR> LTC_NURSERPTTPR { get; set; }
        public virtual DbSet<LTC_NURSINGHANDOVER> LTC_NURSINGHANDOVER { get; set; }
        public virtual DbSet<LTC_NURSINGREC> LTC_NURSINGREC { get; set; }
        public virtual DbSet<LTC_NUTRTION72EVAL> LTC_NUTRTION72EVAL { get; set; }
        public virtual DbSet<LTC_NUTRTIONCAREREC> LTC_NUTRTIONCAREREC { get; set; }
        public virtual DbSet<LTC_NUTRTIONEVAL> LTC_NUTRTIONEVAL { get; set; }
        public virtual DbSet<LTC_ORG> LTC_ORG { get; set; }
        public virtual DbSet<LTC_ORGFLOOR> LTC_ORGFLOOR { get; set; }
        public virtual DbSet<LTC_ORGROOM> LTC_ORGROOM { get; set; }
        public virtual DbSet<LTC_OUTVALUE> LTC_OUTVALUE { get; set; }
        public virtual DbSet<LTC_OWNDRUGDTL> LTC_OWNDRUGDTL { get; set; }
        public virtual DbSet<LTC_OWNDRUGREC> LTC_OWNDRUGREC { get; set; }
        public virtual DbSet<LTC_PAINBODYPART> LTC_PAINBODYPART { get; set; }
        public virtual DbSet<LTC_PAINEVALREC> LTC_PAINEVALREC { get; set; }
        public virtual DbSet<LTC_PAYBILL> LTC_PAYBILL { get; set; }
        public virtual DbSet<LTC_PHARMACISTEVAL> LTC_PHARMACISTEVAL { get; set; }
        public virtual DbSet<LTC_PINMONEY> LTC_PINMONEY { get; set; }
        public virtual DbSet<LTC_PIPELINE> LTC_PIPELINE { get; set; }
        public virtual DbSet<LTC_PIPELINEEVAL> LTC_PIPELINEEVAL { get; set; }
        public virtual DbSet<LTC_PIPELINEREC> LTC_PIPELINEREC { get; set; }
        public virtual DbSet<LTC_PRECHARGE> LTC_PRECHARGE { get; set; }
        public virtual DbSet<LTC_PREIPD> LTC_PREIPD { get; set; }
        public virtual DbSet<LTC_PROPOSALDISSCUSS> LTC_PROPOSALDISSCUSS { get; set; }
        public virtual DbSet<LTC_PROPOSALDISSCUSSREC> LTC_PROPOSALDISSCUSSREC { get; set; }
        public virtual DbSet<LTC_PUSHTOKEN> LTC_PUSHTOKEN { get; set; }
        public virtual DbSet<LTC_QUESTION> LTC_QUESTION { get; set; }
        public virtual DbSet<LTC_QUESTIONRESULTS> LTC_QUESTIONRESULTS { get; set; }
        public virtual DbSet<LTC_RECEIPTS> LTC_RECEIPTS { get; set; }
        public virtual DbSet<LTC_REFERRALREC> LTC_REFERRALREC { get; set; }
        public virtual DbSet<LTC_REFUND> LTC_REFUND { get; set; }
        public virtual DbSet<LTC_REGACTIVITYREQUEVAL> LTC_REGACTIVITYREQUEVAL { get; set; }
        public virtual DbSet<LTC_REGATTACHFILE> LTC_REGATTACHFILE { get; set; }
        public virtual DbSet<LTC_REGDEMAND> LTC_REGDEMAND { get; set; }
        public virtual DbSet<LTC_REGDISEASEHIS> LTC_REGDISEASEHIS { get; set; }
        public virtual DbSet<LTC_REGDISEASEHISDTL> LTC_REGDISEASEHISDTL { get; set; }
        public virtual DbSet<LTC_REGEVALUATE> LTC_REGEVALUATE { get; set; }
        public virtual DbSet<LTC_REGFILE> LTC_REGFILE { get; set; }
        public virtual DbSet<LTC_REGHEALTH> LTC_REGHEALTH { get; set; }
        public virtual DbSet<LTC_REGINSDTL> LTC_REGINSDTL { get; set; }
        public virtual DbSet<LTC_REGNCIINFO> LTC_REGNCIINFO { get; set; }
        public virtual DbSet<LTC_REGQUESTION> LTC_REGQUESTION { get; set; }
        public virtual DbSet<LTC_REGQUESTIONDATA> LTC_REGQUESTIONDATA { get; set; }
        public virtual DbSet<LTC_REGRELATION> LTC_REGRELATION { get; set; }
        public virtual DbSet<LTC_REGRELATIONDTL> LTC_REGRELATIONDTL { get; set; }
        public virtual DbSet<LTC_REHABILITREC> LTC_REHABILITREC { get; set; }
        public virtual DbSet<LTC_RESIDENTBALANCE> LTC_RESIDENTBALANCE { get; set; }
        public virtual DbSet<LTC_RESIDENTBALANCEREFUND> LTC_RESIDENTBALANCEREFUND { get; set; }
        public virtual DbSet<LTC_RESOURCELINKREC> LTC_RESOURCELINKREC { get; set; }
        public virtual DbSet<LTC_ROLES> LTC_ROLES { get; set; }
        public virtual DbSet<LTC_SCENARIO> LTC_SCENARIO { get; set; }
        public virtual DbSet<LTC_SCENARIO_ITEM> LTC_SCENARIO_ITEM { get; set; }
        public virtual DbSet<LTC_SCENARIO_ITEM_OPTION> LTC_SCENARIO_ITEM_OPTION { get; set; }
        public virtual DbSet<LTC_SERVICERECORD> LTC_SERVICERECORD { get; set; }
        public virtual DbSet<LTC_SUBSIDYREC> LTC_SUBSIDYREC { get; set; }
        public virtual DbSet<LTC_SYMPOTMITEM> LTC_SYMPOTMITEM { get; set; }
        public virtual DbSet<LTC_TRANSFERVISIT> LTC_TRANSFERVISIT { get; set; }
        public virtual DbSet<LTC_UNPLANEDIPD> LTC_UNPLANEDIPD { get; set; }
        public virtual DbSet<LTC_UNPLANWEIGHTIND> LTC_UNPLANWEIGHTIND { get; set; }
        public virtual DbSet<LTC_USERS> LTC_USERS { get; set; }
        public virtual DbSet<LTC_VACCINEINJECT> LTC_VACCINEINJECT { get; set; }
        public virtual DbSet<LTC_VISITDEPT> LTC_VISITDEPT { get; set; }
        public virtual DbSet<LTC_VISITDOCRECORDS> LTC_VISITDOCRECORDS { get; set; }
        public virtual DbSet<LTC_VISITDOCTOR> LTC_VISITDOCTOR { get; set; }
        public virtual DbSet<LTC_VISITHOSPITAL> LTC_VISITHOSPITAL { get; set; }
        public virtual DbSet<LTC_VISITPRESCRIPTION> LTC_VISITPRESCRIPTION { get; set; }
        public virtual DbSet<LTC_VITALSIGN> LTC_VITALSIGN { get; set; }
        public virtual DbSet<LTC_WORKITEM> LTC_WORKITEM { get; set; }
        public virtual DbSet<LTC_WORKSUBITEM> LTC_WORKSUBITEM { get; set; }
        public virtual DbSet<LTC_ZIPFILE> LTC_ZIPFILE { get; set; }
        public virtual DbSet<NCI_AGENCY> NCI_AGENCY { get; set; }
        public virtual DbSet<NCI_AGENCYSTAFF> NCI_AGENCYSTAFF { get; set; }
        public virtual DbSet<NCI_CARETYPE> NCI_CARETYPE { get; set; }
        public virtual DbSet<NCI_CODEDTL> NCI_CODEDTL { get; set; }
        public virtual DbSet<NCI_CODEFILE> NCI_CODEFILE { get; set; }
        public virtual DbSet<NCI_COMMFILE> NCI_COMMFILE { get; set; }
        public virtual DbSet<NCI_DRUG> NCI_DRUG { get; set; }
        public virtual DbSet<NCI_DRUGBAK> NCI_DRUGBAK { get; set; }
        public virtual DbSet<NCI_ERRORCODE> NCI_ERRORCODE { get; set; }
        public virtual DbSet<NCI_GOVERNMENT> NCI_GOVERNMENT { get; set; }
        public virtual DbSet<NCI_GOVERNMENTLEVEL> NCI_GOVERNMENTLEVEL { get; set; }
        public virtual DbSet<NCI_GOVERNMENTSTAFF> NCI_GOVERNMENTSTAFF { get; set; }
        public virtual DbSet<NCI_INSURANCECOMPANY> NCI_INSURANCECOMPANY { get; set; }
        public virtual DbSet<NCI_INSURANCECOMPANYSTAFF> NCI_INSURANCECOMPANYSTAFF { get; set; }
        public virtual DbSet<NCI_LOCATIONCODE> NCI_LOCATIONCODE { get; set; }
        public virtual DbSet<NCI_MEDICALMATERIAL> NCI_MEDICALMATERIAL { get; set; }
        public virtual DbSet<NCI_MEDICALMATERIALBAK> NCI_MEDICALMATERIALBAK { get; set; }
        public virtual DbSet<NCI_MODULES> NCI_MODULES { get; set; }
        public virtual DbSet<NCI_NURSINGHOME> NCI_NURSINGHOME { get; set; }
        public virtual DbSet<NCI_NURSINGHOMESTAFF> NCI_NURSINGHOMESTAFF { get; set; }
        public virtual DbSet<NCI_ROLE> NCI_ROLE { get; set; }
        public virtual DbSet<NCI_ROLE_MODULE> NCI_ROLE_MODULE { get; set; }
        public virtual DbSet<NCI_SERVICE> NCI_SERVICE { get; set; }
        public virtual DbSet<NCI_SERVICEBAK> NCI_SERVICEBAK { get; set; }
        public virtual DbSet<NCI_SUPERVISE> NCI_SUPERVISE { get; set; }
        public virtual DbSet<NCI_USER> NCI_USER { get; set; }
        public virtual DbSet<NCIA_AGENCYASSTRECORD> NCIA_AGENCYASSTRECORD { get; set; }
        public virtual DbSet<NCIA_AGENCYASSTRECORDDETAIL> NCIA_AGENCYASSTRECORDDETAIL { get; set; }
        public virtual DbSet<NCIA_APPCERT> NCIA_APPCERT { get; set; }
        public virtual DbSet<NCIA_APPHOSP> NCIA_APPHOSP { get; set; }
        public virtual DbSet<NCIA_APPLICANT> NCIA_APPLICANT { get; set; }
        public virtual DbSet<NCIA_APPLICANTHISTORY> NCIA_APPLICANTHISTORY { get; set; }
        public virtual DbSet<NCIA_CARETYPECONDITION> NCIA_CARETYPECONDITION { get; set; }
        public virtual DbSet<NCIA_DEDUCTION> NCIA_DEDUCTION { get; set; }
        public virtual DbSet<NCIA_NSAPPCERTRATE> NCIA_NSAPPCERTRATE { get; set; }
        public virtual DbSet<NCIA_NSAPPHOSPRATE> NCIA_NSAPPHOSPRATE { get; set; }
        public virtual DbSet<NCIA_NURSINGHOMEASSTRECORD> NCIA_NURSINGHOMEASSTRECORD { get; set; }
        public virtual DbSet<NCIA_NURSINGHOMEASSTRECORDDETAIL> NCIA_NURSINGHOMEASSTRECORDDETAIL { get; set; }
        public virtual DbSet<NCIP_NCIPAYGRANT> NCIP_NCIPAYGRANT { get; set; }
        public virtual DbSet<NCIP_NSMONFEE> NCIP_NSMONFEE { get; set; }
        public virtual DbSet<NCIP_RESIDENTMONFEE> NCIP_RESIDENTMONFEE { get; set; }
        public virtual DbSet<NCIP_RESIDENTMONFEEDTL> NCIP_RESIDENTMONFEEDTL { get; set; }
        public virtual DbSet<NCIP_SERVICEDEPOSIT> NCIP_SERVICEDEPOSIT { get; set; }
        public virtual DbSet<NCIP_SERVICEDEPOSITGRANT> NCIP_SERVICEDEPOSITGRANT { get; set; }
        public virtual DbSet<SYS_CODERULE> SYS_CODERULE { get; set; }
        public virtual DbSet<SYS_REPORT> SYS_REPORT { get; set; }
        public virtual DbSet<TSG_ANSWER> TSG_ANSWER { get; set; }
        public virtual DbSet<TSG_ANSWERDTL> TSG_ANSWERDTL { get; set; }
        public virtual DbSet<TSG_CATEGORY> TSG_CATEGORY { get; set; }
        public virtual DbSet<TSG_QUESTION> TSG_QUESTION { get; set; }
    
        public virtual int UPDATEAPPLICANTID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEAPPLICANTID");
        }
    }
}
