//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_SUPERVISE
    {
        public int ID { get; set; }
        public string APPLICANTID { get; set; }
        public Nullable<int> APPCERTID { get; set; }
        public Nullable<int> APPHOSPID { get; set; }
        public int TYPE { get; set; }
        public string REASON { get; set; }
        public string RESTORE { get; set; }
        public int STATUS { get; set; }
        public bool VALID { get; set; }
        public Nullable<System.DateTime> CANCLETIME { get; set; }
        public Nullable<System.DateTime> RESTORETIME { get; set; }
        public string CREATEBY { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    }
}
