//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_DRUG
    {
        public string DRUGCODE { get; set; }
        public string MCRULEID { get; set; }
        public string CNNAME { get; set; }
        public string ENNAME { get; set; }
        public string DRUGTYPE { get; set; }
        public string MCTYPE { get; set; }
        public string SFDAAPPROVALNO { get; set; }
        public bool ISPRESCRIPTION { get; set; }
        public bool ISCHINAPRODUCT { get; set; }
        public string ORGIN { get; set; }
        public string MANUFACTURER { get; set; }
        public string SPEC { get; set; }
        public string UNITS { get; set; }
        public string FORM { get; set; }
        public Nullable<int> CONVERSIONRATIO { get; set; }
        public string MINPACKAGE { get; set; }
        public Nullable<int> STANDARDUSAGE { get; set; }
        public string PROVIDER { get; set; }
        public string FREQUENCY { get; set; }
        public string DRUGUSAGEMODE { get; set; }
        public string DRUGUSAGE { get; set; }
        public string ADVERSEREACTION { get; set; }
        public string ATTENTION { get; set; }
        public string ATTENTIONOLDMAN { get; set; }
        public Nullable<decimal> GUIDEPRICE { get; set; }
        public Nullable<decimal> MAXPRICE { get; set; }
        public Nullable<int> NCIMONTHLYMAXUSAGE { get; set; }
        public string COMMENT { get; set; }
        public string PINYIN { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    }
}
