//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_AGENCY
    {
        public NCI_AGENCY()
        {
            this.NCI_AGENCYSTAFF = new HashSet<NCI_AGENCYSTAFF>();
        }
    
        public string AGENCYID { get; set; }
        public string GOVID { get; set; }
        public string AGENCYNAME { get; set; }
        public string AGENCYNO { get; set; }
        public string CONTACT { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string CREATBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCI_GOVERNMENT NCI_GOVERNMENT { get; set; }
        public virtual ICollection<NCI_AGENCYSTAFF> NCI_AGENCYSTAFF { get; set; }
    }
}
