//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_SERVICEBAK
    {
        public string SERVICECODE { get; set; }
        public string MCRULEID { get; set; }
        public string SERVICENAME { get; set; }
        public string SERVICEDESC { get; set; }
        public string UNITS { get; set; }
        public Nullable<decimal> GUIDEPRICE { get; set; }
        public Nullable<decimal> MAXPRICE { get; set; }
        public string COMMENT { get; set; }
        public string PINYIN { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> BAKTIME { get; set; }
        public string BAKBY { get; set; }
    }
}
