//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_NURSINGHOMESTAFF
    {
        public string NSSTAFFID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string NSID { get; set; }
        public string DEPARMENT { get; set; }
        public string POSITION { get; set; }
        public string LEVEL { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCI_NURSINGHOME NCI_NURSINGHOME { get; set; }
        public virtual NCI_USER NCI_USER { get; set; }
    }
}
