//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_CARETYPE
    {
        public NCI_CARETYPE()
        {
            this.NCIA_CARETYPECONDITION = new HashSet<NCIA_CARETYPECONDITION>();
            this.NCI_NURSINGHOME = new HashSet<NCI_NURSINGHOME>();
        }
    
        public int CARETYPEID { get; set; }
        public int CARETYPE { get; set; }
        public string DISPLAYNAME { get; set; }
        public string CARETYPENAME { get; set; }
        public decimal NCIPAYLEVEL { get; set; }
        public decimal NCIPAYLEVELOUT { get; set; }
        public decimal NCIPAYSCALE { get; set; }
        public decimal NCIPAYSCALEOUT { get; set; }
    
        public virtual ICollection<NCIA_CARETYPECONDITION> NCIA_CARETYPECONDITION { get; set; }
        public virtual ICollection<NCI_NURSINGHOME> NCI_NURSINGHOME { get; set; }
    }
}
