//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_MEDICALMATERIALBAK
    {
        public string MATERIALCODE { get; set; }
        public string MCRULEID { get; set; }
        public string MATERIALTYPE { get; set; }
        public string MATERIALNAME { get; set; }
        public string MATERIALLEVEL { get; set; }
        public bool ISCHINAPRODUCT { get; set; }
        public string ORGIN { get; set; }
        public string MANUFACTURER { get; set; }
        public string SPEC { get; set; }
        public string UNITS { get; set; }
        public string USAGE { get; set; }
        public string ATTENTION { get; set; }
        public Nullable<decimal> GUIDEPRICE { get; set; }
        public Nullable<decimal> MAXPRICE { get; set; }
        public Nullable<int> NCIMONTHLYMAXUSAGE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public string PINYIN { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> BAKTIME { get; set; }
        public string BAKBY { get; set; }
    }
}
