//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_APPCERT
    {
        public NCIA_APPCERT()
        {
            this.NCIA_APPHOSP = new HashSet<NCIA_APPHOSP>();
            this.NCIA_CARETYPECONDITION = new HashSet<NCIA_CARETYPECONDITION>();
        }
    
        public int APPCERTID { get; set; }
        public string APPLICANTID { get; set; }
        public Nullable<int> BASEAPPCERTIDOFREAPP { get; set; }
        public Nullable<int> AGENCYASSTRECORDID { get; set; }
        public Nullable<int> NSASSTRECORDID { get; set; }
        public string NSID { get; set; }
        public string APPCERTSN { get; set; }
        public string NAME { get; set; }
        public string GENDER { get; set; }
        public int AGE { get; set; }
        public string IDNO { get; set; }
        public string SSNO { get; set; }
        public int NSAPPCARETYPE { get; set; }
        public int MCTYPE { get; set; }
        public string DISEASE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> AGENCYAPPROVEDCARETYPE { get; set; }
        public string APPREASON { get; set; }
        public int STATUS { get; set; }
        public string UPLOADFILES { get; set; }
        public string NSCOMMENT { get; set; }
        public System.DateTime NSOPERATETIME { get; set; }
        public int NSUSERID { get; set; }
        public Nullable<int> ICRESULT { get; set; }
        public string ICCOMMENT { get; set; }
        public Nullable<System.DateTime> ICOPERATETIME { get; set; }
        public Nullable<int> ICUSERID { get; set; }
        public string ICID { get; set; }
        public Nullable<int> AGENCYRESULT { get; set; }
        public string AGENCYCOMMENT { get; set; }
        public Nullable<System.DateTime> AGENCYOPERATETIME { get; set; }
        public Nullable<int> AGENCYUSERID { get; set; }
        public string AGENCYID { get; set; }
        public string CERTNO { get; set; }
        public Nullable<System.DateTime> EVALUATIONTIME { get; set; }
        public Nullable<System.DateTime> CERTSTARTTIME { get; set; }
        public Nullable<System.DateTime> CERTEXPIREDTIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCI_NURSINGHOME NCI_NURSINGHOME { get; set; }
        public virtual NCIA_AGENCYASSTRECORD NCIA_AGENCYASSTRECORD { get; set; }
        public virtual NCIA_APPLICANT NCIA_APPLICANT { get; set; }
        public virtual NCIA_NURSINGHOMEASSTRECORD NCIA_NURSINGHOMEASSTRECORD { get; set; }
        public virtual ICollection<NCIA_APPHOSP> NCIA_APPHOSP { get; set; }
        public virtual ICollection<NCIA_CARETYPECONDITION> NCIA_CARETYPECONDITION { get; set; }
    }
}
