//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_NURSINGHOMEASSTRECORDDETAIL
    {
        public int NSASSTRECORDDETAILID { get; set; }
        public Nullable<int> NSASSTRECORDID { get; set; }
        public int QUESTIONID { get; set; }
        public Nullable<decimal> MAKERVALUE { get; set; }
        public int MAKERID { get; set; }
        public Nullable<int> LIMITEDVALUEID { get; set; }
    
        public virtual NCIA_NURSINGHOMEASSTRECORD NCIA_NURSINGHOMEASSTRECORD { get; set; }
    }
}
