//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_NSAPPCERTRATE
    {
        public int ID { get; set; }
        public string NSID { get; set; }
        public decimal PASSRATE { get; set; }
        public string YEAR { get; set; }
        public long TOTALPEOPLE { get; set; }
        public long PASSPEOPLE { get; set; }
        public System.DateTime UPDATETIME { get; set; }
    
        public virtual NCI_NURSINGHOME NCI_NURSINGHOME { get; set; }
    }
}
