//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_CARETYPECONDITION
    {
        public NCIA_CARETYPECONDITION()
        {
            this.NCIA_APPCERT = new HashSet<NCIA_APPCERT>();
        }
    
        public int CCCID { get; set; }
        public string NSID { get; set; }
        public int CARETYPEID { get; set; }
        public string CCCNAME { get; set; }
        public string CCCDESC { get; set; }
    
        public virtual NCI_CARETYPE NCI_CARETYPE { get; set; }
        public virtual NCI_NURSINGHOME NCI_NURSINGHOME { get; set; }
        public virtual ICollection<NCIA_APPCERT> NCIA_APPCERT { get; set; }
    }
}
