//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_NSMONFEE
    {
        public NCIP_NSMONFEE()
        {
            this.NCIA_DEDUCTION = new HashSet<NCIA_DEDUCTION>();
            this.NCIP_RESIDENTMONFEE = new HashSet<NCIP_RESIDENTMONFEE>();
        }
    
        public long NSMONFEEID { get; set; }
        public Nullable<int> NCIPAYGRANTID { get; set; }
        public string NSID { get; set; }
        public string NSNO { get; set; }
        public string YEARMONTH { get; set; }
        public int TOTALRESIDENT { get; set; }
        public int TOTALHOSPDAY { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public decimal TOTALNCIPAY { get; set; }
        public int STATUS { get; set; }
        public string CREATORNAME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCIA_DEDUCTION> NCIA_DEDUCTION { get; set; }
        public virtual NCIP_NCIPAYGRANT NCIP_NCIPAYGRANT { get; set; }
        public virtual ICollection<NCIP_RESIDENTMONFEE> NCIP_RESIDENTMONFEE { get; set; }
    }
}
