//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_RESIDENTMONFEE
    {
        public NCIP_RESIDENTMONFEE()
        {
            this.NCIP_RESIDENTMONFEEDTL = new HashSet<NCIP_RESIDENTMONFEEDTL>();
        }
    
        public long RSMONFEEID { get; set; }
        public Nullable<long> NSMONFEEID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string NSID { get; set; }
        public Nullable<int> CARETYPE { get; set; }
        public string RESIDENTSSID { get; set; }
        public string CERTNO { get; set; }
        public System.DateTime HOSPENTRYDATE { get; set; }
        public System.DateTime HOSPDISCHARGEDATE { get; set; }
        public int HOSPDAY { get; set; }
        public decimal NCIPAYLEVEL { get; set; }
        public decimal NCIPAYSCALE { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public decimal NCIPAY { get; set; }
        public int STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCIP_NSMONFEE NCIP_NSMONFEE { get; set; }
        public virtual ICollection<NCIP_RESIDENTMONFEEDTL> NCIP_RESIDENTMONFEEDTL { get; set; }
    }
}
