//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_SERVICEDEPOSITGRANT
    {
        public NCIP_SERVICEDEPOSITGRANT()
        {
            this.NCIP_SERVICEDEPOSIT = new HashSet<NCIP_SERVICEDEPOSIT>();
        }
    
        public int SDGRANTID { get; set; }
        public string NSID { get; set; }
        public string YEAR { get; set; }
        public decimal DUEOFPAY { get; set; }
        public decimal ACTRUALPAY { get; set; }
        public Nullable<decimal> DECUT { get; set; }
        public string DECUTREASON { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCIP_SERVICEDEPOSIT> NCIP_SERVICEDEPOSIT { get; set; }
    }
}
