//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CODERULE
    {
        public string ORGID { get; set; }
        public string CODEKEY { get; set; }
        public string FLAGRULE { get; set; }
        public string GENERATERULE { get; set; }
        public string FLAG { get; set; }
        public Nullable<int> SERIALNUMBER { get; set; }
    }
}
