//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_REPORT
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string MAJORTYPE { get; set; }
        public string REPORTTYPE { get; set; }
        public string FilterType { get; set; }
        public Nullable<bool> IsFeeNoRequired { get; set; }
        public string SYSTYPE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string ORGID { get; set; }
    }
}
