//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSG_CATEGORY
    {
        public TSG_CATEGORY()
        {
            this.TSG_QUESTION = new HashSet<TSG_QUESTION>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<TSG_QUESTION> TSG_QUESTION { get; set; }
    }
}
