//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSG_ANSWER
    {
        public TSG_ANSWER()
        {
            this.TSG_ANSWERDTL = new HashSet<TSG_ANSWERDTL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDERSEQ { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATER { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TSG_QUESTION TSG_QUESTION { get; set; }
        public virtual ICollection<TSG_ANSWERDTL> TSG_ANSWERDTL { get; set; }
    }
}
